-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/account.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM delta_scan('${DELTA_BASE}/silver/account')
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "account_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."text"')) AS "type_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."coding"')[1:1], '$."code"')) AS "type_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."coding"')[1:1], '$."system"')) AS "type_system",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."name"')) AS "name",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."subject"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS VARCHAR) AS "subject_ids",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."owner"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS "owner_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."owner"'), '$."reference"')) AS "owner_reference",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."description"')) AS "description",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."partOf"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS "part_of_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."partOf"'), '$."reference"')) AS "part_of_reference"
FROM sof_src;
