-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/claim_response.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM delta_scan('${DELTA_BASE}/silver/claimresponse')
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "claim_response_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."text"')) AS "type_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."coding"')[1:1], '$."code"')) AS "type_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."coding"')[1:1], '$."system"')) AS "type_system",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."subType"'), '$."text"')) AS "sub_type_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."subType"'), '$."coding"')[1:1], '$."code"')) AS "sub_type_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."subType"'), '$."coding"')[1:1], '$."system"')) AS "sub_type_system",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."use"')) AS "use",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."patient"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS "patient_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."patient"'), '$."reference"')) AS "patient_reference",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."created"')) AS "created",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."insurer"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS "insurer_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."insurer"'), '$."reference"')) AS "insurer_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."requestor"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS "requestor_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."requestor"'), '$."reference"')) AS "requestor_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."request"'), sof_r7 -> to_json(nullif(regexp_extract(json_extract_string(sof_r7, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y8 -> sof_y8 IS NOT NULL)) AS "request_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."request"'), '$."reference"')) AS "request_reference",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."outcome"')) AS "outcome",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."disposition"')) AS "disposition",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."preAuthRef"')) AS "pre_auth_ref",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."payeeType"'), '$."text"')) AS "payee_type_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."payeeType"'), '$."coding"')[1:1], '$."code"')) AS "payee_type_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."payeeType"'), '$."coding"')[1:1], '$."system"')) AS "payee_type_system",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."fundsReserve"'), '$."text"')) AS "funds_reserve_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."fundsReserve"'), '$."coding"')[1:1], '$."code"')) AS "funds_reserve_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."fundsReserve"'), '$."coding"')[1:1], '$."system"')) AS "funds_reserve_system",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."formCode"'), '$."text"')) AS "form_code_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."formCode"'), '$."coding"')[1:1], '$."code"')) AS "form_code_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."formCode"'), '$."coding"')[1:1], '$."system"')) AS "form_code_system",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."communicationRequest"'), sof_r9 -> to_json(nullif(regexp_extract(json_extract_string(sof_r9, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y10 -> sof_y10 IS NOT NULL)) AS VARCHAR) AS "communication_request_ids"
FROM sof_src;
