-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/consent.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM delta_scan('${DELTA_BASE}/silver/consent')
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "consent_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."scope"'), '$."text"')) AS "scope_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."scope"'), '$."coding"')[1:1], '$."code"')) AS "scope_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."scope"'), '$."coding"')[1:1], '$."system"')) AS "scope_system",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."patient"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS "patient_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."patient"'), '$."reference"')) AS "patient_reference",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."dateTime"')) AS "date_time",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."performer"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS VARCHAR) AS "performer_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."organization"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS VARCHAR) AS "organization_ids",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."sourceReference"'), sof_r7 -> to_json(nullif(regexp_extract(json_extract_string(sof_r7, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y8 -> sof_y8 IS NOT NULL)) AS "source_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."policyRule"'), '$."text"')) AS "policy_rule_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."policyRule"'), '$."coding"')[1:1], '$."code"')) AS "policy_rule_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."policyRule"'), '$."coding"')[1:1], '$."system"')) AS "policy_rule_system"
FROM sof_src;
