-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/diagnostic_report.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM delta_scan('${DELTA_BASE}/silver/diagnosticreport')
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "diagnostic_report_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."basedOn"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS VARCHAR) AS "based_on_ids",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."code"'), '$."text"')) AS "code_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."code"'), '$."coding"')[1:1], '$."code"')) AS "code_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."code"'), '$."coding"')[1:1], '$."system"')) AS "code_system",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."subject"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS "subject_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."subject"'), '$."reference"')) AS "subject_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."encounter"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS "encounter_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."encounter"'), '$."reference"')) AS "encounter_reference",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."effectiveDateTime"')) AS "effective_date_time",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."issued"')) AS "issued",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."performer"'), sof_r7 -> to_json(nullif(regexp_extract(json_extract_string(sof_r7, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y8 -> sof_y8 IS NOT NULL)) AS VARCHAR) AS "performer_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."resultsInterpreter"'), sof_r9 -> to_json(nullif(regexp_extract(json_extract_string(sof_r9, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y10 -> sof_y10 IS NOT NULL)) AS VARCHAR) AS "results_interpreter_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."specimen"'), sof_r11 -> to_json(nullif(regexp_extract(json_extract_string(sof_r11, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y12 -> sof_y12 IS NOT NULL)) AS VARCHAR) AS "specimen_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."result"'), sof_r13 -> to_json(nullif(regexp_extract(json_extract_string(sof_r13, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y14 -> sof_y14 IS NOT NULL)) AS VARCHAR) AS "result_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."imagingStudy"'), sof_r15 -> to_json(nullif(regexp_extract(json_extract_string(sof_r15, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y16 -> sof_y16 IS NOT NULL)) AS VARCHAR) AS "imaging_study_ids",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."conclusion"')) AS "conclusion"
FROM sof_src;
