-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/enrollment_request.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM delta_scan('${DELTA_BASE}/silver/enrollmentrequest')
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "enrollment_request_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."created"')) AS "created",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."insurer"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS "insurer_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."insurer"'), '$."reference"')) AS "insurer_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."provider"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS "provider_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."provider"'), '$."reference"')) AS "provider_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."candidate"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS "candidate_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."candidate"'), '$."reference"')) AS "candidate_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."coverage"'), sof_r7 -> to_json(nullif(regexp_extract(json_extract_string(sof_r7, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y8 -> sof_y8 IS NOT NULL)) AS "coverage_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."coverage"'), '$."reference"')) AS "coverage_reference"
FROM sof_src;
