-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/measure_report.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM delta_scan('${DELTA_BASE}/silver/measurereport')
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "measure_report_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."type"')) AS "type",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."measure"')) AS "measure",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."subject"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS "subject_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."subject"'), '$."reference"')) AS "subject_reference",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."date"')) AS "date",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."reporter"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS "reporter_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."reporter"'), '$."reference"')) AS "reporter_reference",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."improvementNotation"'), '$."text"')) AS "improvement_notation_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."improvementNotation"'), '$."coding"')[1:1], '$."code"')) AS "improvement_notation_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."improvementNotation"'), '$."coding"')[1:1], '$."system"')) AS "improvement_notation_system",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."evaluatedResource"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS VARCHAR) AS "evaluated_resource_ids"
FROM sof_src;
