-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/medication_statement.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM delta_scan('${DELTA_BASE}/silver/medicationstatement')
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "medication_statement_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."basedOn"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS VARCHAR) AS "based_on_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."partOf"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS VARCHAR) AS "part_of_ids",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."category"'), '$."text"')) AS "category_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."category"'), '$."coding"')[1:1], '$."code"')) AS "category_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."category"'), '$."coding"')[1:1], '$."system"')) AS "category_system",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."medicationReference"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS "medication_id",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."subject"'), sof_r7 -> to_json(nullif(regexp_extract(json_extract_string(sof_r7, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y8 -> sof_y8 IS NOT NULL)) AS "subject_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."subject"'), '$."reference"')) AS "subject_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."context"'), sof_r9 -> to_json(nullif(regexp_extract(json_extract_string(sof_r9, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y10 -> sof_y10 IS NOT NULL)) AS "context_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."context"'), '$."reference"')) AS "context_reference",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."effectiveDateTime"')) AS "effective_date_time",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."dateAsserted"')) AS "date_asserted",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."informationSource"'), sof_r11 -> to_json(nullif(regexp_extract(json_extract_string(sof_r11, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y12 -> sof_y12 IS NOT NULL)) AS "information_source_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."informationSource"'), '$."reference"')) AS "information_source_reference",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."derivedFrom"'), sof_r13 -> to_json(nullif(regexp_extract(json_extract_string(sof_r13, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y14 -> sof_y14 IS NOT NULL)) AS VARCHAR) AS "derived_from_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."reasonReference"'), sof_r15 -> to_json(nullif(regexp_extract(json_extract_string(sof_r15, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y16 -> sof_y16 IS NOT NULL)) AS VARCHAR) AS "reason_reference_ids"
FROM sof_src;
