-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/medicinal_product.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM delta_scan('${DELTA_BASE}/silver/medicinalproduct')
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "medicinal_product_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."text"')) AS "type_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."coding"')[1:1], '$."code"')) AS "type_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."coding"')[1:1], '$."system"')) AS "type_system",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."domain"'), '$."code"')) AS "domain_code",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."domain"'), '$."system"')) AS "domain_system",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."domain"'), '$."display"')) AS "domain_display",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."combinedPharmaceuticalDoseForm"'), '$."text"')) AS "combined_pharmaceutical_dose_form_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."combinedPharmaceuticalDoseForm"'), '$."coding"')[1:1], '$."code"')) AS "combined_pharmaceutical_dose_form_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."combinedPharmaceuticalDoseForm"'), '$."coding"')[1:1], '$."system"')) AS "combined_pharmaceutical_dose_form_system",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."legalStatusOfSupply"'), '$."text"')) AS "legal_status_of_supply_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."legalStatusOfSupply"'), '$."coding"')[1:1], '$."code"')) AS "legal_status_of_supply_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."legalStatusOfSupply"'), '$."coding"')[1:1], '$."system"')) AS "legal_status_of_supply_system",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."additionalMonitoringIndicator"'), '$."text"')) AS "additional_monitoring_indicator_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."additionalMonitoringIndicator"'), '$."coding"')[1:1], '$."code"')) AS "additional_monitoring_indicator_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."additionalMonitoringIndicator"'), '$."coding"')[1:1], '$."system"')) AS "additional_monitoring_indicator_system",
  CAST(to_json(sof_get(sof_wrap(sof_src.resource), '$."specialMeasures"')) AS VARCHAR) AS "special_measures",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."paediatricUseIndicator"'), '$."text"')) AS "paediatric_use_indicator_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."paediatricUseIndicator"'), '$."coding"')[1:1], '$."code"')) AS "paediatric_use_indicator_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."paediatricUseIndicator"'), '$."coding"')[1:1], '$."system"')) AS "paediatric_use_indicator_system",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."pharmaceuticalProduct"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS VARCHAR) AS "pharmaceutical_product_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."packagedMedicinalProduct"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS VARCHAR) AS "packaged_medicinal_product_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."attachedDocument"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS VARCHAR) AS "attached_document_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."masterFile"'), sof_r7 -> to_json(nullif(regexp_extract(json_extract_string(sof_r7, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y8 -> sof_y8 IS NOT NULL)) AS VARCHAR) AS "master_file_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."contact"'), sof_r9 -> to_json(nullif(regexp_extract(json_extract_string(sof_r9, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y10 -> sof_y10 IS NOT NULL)) AS VARCHAR) AS "contact_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."clinicalTrial"'), sof_r11 -> to_json(nullif(regexp_extract(json_extract_string(sof_r11, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y12 -> sof_y12 IS NOT NULL)) AS VARCHAR) AS "clinical_trial_ids"
FROM sof_src;
