-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/operation_definition.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM delta_scan('${DELTA_BASE}/silver/operationdefinition')
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "operation_definition_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."url"')) AS "url",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."version"')) AS "version",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."name"')) AS "name",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."title"')) AS "title",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."kind"')) AS "kind",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."experimental"')) AS BOOLEAN) AS "experimental",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."date"')) AS "date",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."publisher"')) AS "publisher",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."description"')) AS "description",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."purpose"')) AS "purpose",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."affectsState"')) AS BOOLEAN) AS "affects_state",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."code"')) AS "code",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."comment"')) AS "comment",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."base"')) AS "base",
  CAST(to_json(sof_get(sof_wrap(sof_src.resource), '$."resource"')) AS VARCHAR) AS "resource",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."system"')) AS BOOLEAN) AS "system",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."type"')) AS BOOLEAN) AS "type",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."instance"')) AS BOOLEAN) AS "instance",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."inputProfile"')) AS "input_profile",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."outputProfile"')) AS "output_profile"
FROM sof_src;
