-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/patient.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM delta_scan('${DELTA_BASE}/silver/patient')
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "patient_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."active"')) AS BOOLEAN) AS "active",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."gender"')) AS "gender",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."birthDate"')) AS DATE) AS "birth_date",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."deceasedBoolean"')) AS BOOLEAN) AS "deceased_boolean",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."deceasedDateTime"')) AS "deceased_date_time",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."maritalStatus"'), '$."text"')) AS "marital_status_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."maritalStatus"'), '$."coding"')[1:1], '$."code"')) AS "marital_status_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."maritalStatus"'), '$."coding"')[1:1], '$."system"')) AS "marital_status_system",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."multipleBirthBoolean"')) AS BOOLEAN) AS "multiple_birth_boolean",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."multipleBirthInteger"')) AS INTEGER) AS "multiple_birth_integer",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."generalPractitioner"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS VARCHAR) AS "general_practitioner_ids",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."managingOrganization"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS "managing_organization_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."managingOrganization"'), '$."reference"')) AS "managing_organization_reference"
FROM sof_src;
