-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/payment_notice.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM delta_scan('${DELTA_BASE}/silver/paymentnotice')
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "payment_notice_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."request"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS "request_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."request"'), '$."reference"')) AS "request_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."response"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS "response_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."response"'), '$."reference"')) AS "response_reference",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."created"')) AS "created",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."provider"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS "provider_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."provider"'), '$."reference"')) AS "provider_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."payment"'), sof_r7 -> to_json(nullif(regexp_extract(json_extract_string(sof_r7, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y8 -> sof_y8 IS NOT NULL)) AS "payment_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."payment"'), '$."reference"')) AS "payment_reference",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."paymentDate"')) AS DATE) AS "payment_date",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."payee"'), sof_r9 -> to_json(nullif(regexp_extract(json_extract_string(sof_r9, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y10 -> sof_y10 IS NOT NULL)) AS "payee_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."payee"'), '$."reference"')) AS "payee_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."recipient"'), sof_r11 -> to_json(nullif(regexp_extract(json_extract_string(sof_r11, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y12 -> sof_y12 IS NOT NULL)) AS "recipient_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."recipient"'), '$."reference"')) AS "recipient_reference",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."paymentStatus"'), '$."text"')) AS "payment_status_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."paymentStatus"'), '$."coding"')[1:1], '$."code"')) AS "payment_status_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."paymentStatus"'), '$."coding"')[1:1], '$."system"')) AS "payment_status_system"
FROM sof_src;
