-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/practitioner.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM delta_scan('${DELTA_BASE}/silver/practitioner')
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "practitioner_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."active"')) AS BOOLEAN) AS "active",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."gender"')) AS "gender",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."birthDate"')) AS DATE) AS "birth_date"
FROM sof_src;
