-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/substance.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM delta_scan('${DELTA_BASE}/silver/substance')
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "substance_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."code"'), '$."text"')) AS "code_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."code"'), '$."coding"')[1:1], '$."code"')) AS "code_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."code"'), '$."coding"')[1:1], '$."system"')) AS "code_system",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."description"')) AS "description"
FROM sof_src;
