-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/substance_polymer.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM delta_scan('${DELTA_BASE}/silver/substancepolymer')
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "substance_polymer_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."class"'), '$."text"')) AS "class_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."class"'), '$."coding"')[1:1], '$."code"')) AS "class_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."class"'), '$."coding"')[1:1], '$."system"')) AS "class_system",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."geometry"'), '$."text"')) AS "geometry_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."geometry"'), '$."coding"')[1:1], '$."code"')) AS "geometry_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."geometry"'), '$."coding"')[1:1], '$."system"')) AS "geometry_system",
  CAST(to_json(sof_get(sof_wrap(sof_src.resource), '$."modification"')) AS VARCHAR) AS "modification"
FROM sof_src;
