-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/supply_request.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM delta_scan('${DELTA_BASE}/silver/supplyrequest')
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "supply_request_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."category"'), '$."text"')) AS "category_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."category"'), '$."coding"')[1:1], '$."code"')) AS "category_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."category"'), '$."coding"')[1:1], '$."system"')) AS "category_system",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."priority"')) AS "priority",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."itemReference"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS "item_id",
  CAST(sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."quantity"'), '$."value"')) AS DOUBLE) AS "quantity_value",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."quantity"'), '$."unit"')) AS "quantity_unit",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."quantity"'), '$."code"')) AS "quantity_code",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."occurrenceDateTime"')) AS "occurrence_date_time",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."authoredOn"')) AS "authored_on",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."requester"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS "requester_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."requester"'), '$."reference"')) AS "requester_reference",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."supplier"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS VARCHAR) AS "supplier_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."reasonReference"'), sof_r7 -> to_json(nullif(regexp_extract(json_extract_string(sof_r7, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y8 -> sof_y8 IS NOT NULL)) AS VARCHAR) AS "reason_reference_ids",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."deliverFrom"'), sof_r9 -> to_json(nullif(regexp_extract(json_extract_string(sof_r9, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y10 -> sof_y10 IS NOT NULL)) AS "deliver_from_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."deliverFrom"'), '$."reference"')) AS "deliver_from_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."deliverTo"'), sof_r11 -> to_json(nullif(regexp_extract(json_extract_string(sof_r11, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y12 -> sof_y12 IS NOT NULL)) AS "deliver_to_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."deliverTo"'), '$."reference"')) AS "deliver_to_reference"
FROM sof_src;
