-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/test_report.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM delta_scan('${DELTA_BASE}/silver/testreport')
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "test_report_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."identifier"'), '$."value"')) AS "identifier_value",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."identifier"'), '$."system"')) AS "identifier_system",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."name"')) AS "name",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."testScript"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS "test_script_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."testScript"'), '$."reference"')) AS "test_script_reference",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."result"')) AS "result",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."score"')) AS DOUBLE) AS "score",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."tester"')) AS "tester",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."issued"')) AS "issued"
FROM sof_src;
