"""Run the official SQL-on-FHIR shared JSON test suite (vendored under
views/conformance/suite/) against the compiler and produce the conformance report.

Statuses per test:
  pass        — result rows match `expect` (order-insensitive), or the view errored
                where `expectError` is set
  fail        — ran but produced wrong rows
  error       — unexpectedly raised
  unsupported — CompileError on a feature outside the compiled subset (counted
                honestly; these route to the ADR-0027 interpreter fallback at runtime)

`expected_pass.json` is the CI regression gate: every test listed there must pass.
Regenerate it (and REPORT.md) with:  python -m fhirhouse_views.conformance
"""
from __future__ import annotations

import json
import pathlib
from collections import Counter

from .compiler import CompileError
from .runner import connect, run_view

SUITE_DIR = pathlib.Path(__file__).resolve().parent.parent / "conformance" / "suite"
MANIFEST = SUITE_DIR.parent / "expected_pass.json"
REPORT = SUITE_DIR.parent / "REPORT.md"


def _norm(v):
    """Canonicalize for comparison: integral floats → int, recurse containers."""
    if isinstance(v, float) and v.is_integer():
        return int(v)
    if isinstance(v, list):
        return [_norm(x) for x in v]
    if isinstance(v, dict):
        return {k: _norm(x) for k, x in v.items()}
    return v


def _canon_rows(rows: list[dict]) -> list[str]:
    return sorted(json.dumps(_norm(r), sort_keys=True) for r in rows)


def run_test(test: dict, resources: list[dict], con=None) -> tuple[str, str]:
    """Returns (status, detail)."""
    expect_error = bool(test.get("expectError"))
    try:
        names, rows = run_view(test.get("view") or {}, resources, con=con)
    except CompileError as e:
        if expect_error:
            return "pass", f"expected error: {e}"
        return "unsupported", str(e)
    except Exception as e:  # runtime error() calls land here
        if expect_error:
            return "pass", f"expected error: {e}"
        return "error", f"{type(e).__name__}: {str(e)[:200]}"
    if expect_error:
        return "fail", "expected an error but the view ran"
    if "expectColumns" in test and names != test["expectColumns"]:
        return "fail", f"columns {names} != {test['expectColumns']}"
    if "expect" in test:
        got, want = _canon_rows(rows), _canon_rows(test["expect"])
        if got != want:
            return "fail", f"rows mismatch: got {got[:3]}... want {want[:3]}..."
    return "pass", ""


def run_suite(suite_dir: pathlib.Path = SUITE_DIR) -> list[dict]:
    con = connect()
    results = []
    for f in sorted(suite_dir.glob("*.json")):
        doc = json.loads(f.read_text())
        for t in doc["tests"]:
            status, detail = run_test(t, doc.get("resources", []), con=con)
            results.append({"file": f.name, "title": t["title"], "status": status, "detail": detail})
    return results


def write_report(results: list[dict]) -> str:
    counts = Counter(r["status"] for r in results)
    total = len(results)
    lines = [
        "# SQL-on-FHIR v2 conformance report — fhirhouse_views compiler",
        "",
        "Generated by `python -m fhirhouse_views.conformance` against the vendored",
        "official shared test suite (`views/conformance/suite/`). FH-0005's bar.",
        "",
        f"**{counts['pass']}/{total} pass** · {counts.get('fail', 0)} fail · "
        f"{counts.get('error', 0)} error · {counts.get('unsupported', 0)} unsupported "
        "(routed to the ADR-0027 interpreter fallback)",
        "",
        "| file | test | status | detail |",
        "|---|---|---|---|",
    ]
    for r in results:
        if r["status"] != "pass":
            lines.append(f"| {r['file']} | {r['title']} | **{r['status']}** | {r['detail'][:110]} |")
    lines += ["", "Passing tests are omitted from the table; the manifest "
              "`expected_pass.json` lists them and gates CI against regressions."]
    return "\n".join(lines) + "\n"


def main() -> int:
    results = run_suite()
    MANIFEST.write_text(json.dumps(
        sorted(f"{r['file']}::{r['title']}" for r in results if r["status"] == "pass"),
        indent=1) + "\n")
    REPORT.write_text(write_report(results))
    counts = Counter(r["status"] for r in results)
    print(f"conformance: {counts['pass']}/{len(results)} pass, "
          f"{counts.get('fail', 0)} fail, {counts.get('error', 0)} error, "
          f"{counts.get('unsupported', 0)} unsupported -> {REPORT}")
    for r in results:
        if r["status"] in ("fail", "error"):
            print(f"  {r['status'].upper()}: {r['file']} :: {r['title']} — {r['detail'][:140]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
