// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeSystem, CodeSystemConcept } from "../../hl7-fhir-r4-core/CodeSystem";

import {
    buildResource,
    ensureProfile,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type Shareable_CodeSystemProfileRaw = {
    url: string;
    version: string;
    name: string;
    status: ("draft" | "active" | "retired" | "unknown");
    experimental: boolean;
    publisher: string;
    description: string;
    concept: CodeSystemConcept[];
    content: ("not-present" | "example" | "fragment" | "complete" | "supplement");
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/shareablecodesystem (pkg: hl7.fhir.r4.core#4.0.1)
export class Shareable_CodeSystemProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/shareablecodesystem";

    private resource: CodeSystem;

    constructor (resource: CodeSystem) {
        this.resource = resource;
    }

    static from (resource: CodeSystem) : Shareable_CodeSystemProfile {
        if (!resource.meta?.profile?.includes(Shareable_CodeSystemProfile.canonicalUrl)) {
            throw new Error(`Shareable_CodeSystemProfile: meta.profile must include ${Shareable_CodeSystemProfile.canonicalUrl}`)
        }
        const profile = new Shareable_CodeSystemProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: CodeSystem) : Shareable_CodeSystemProfile {
        ensureProfile(resource, Shareable_CodeSystemProfile.canonicalUrl);
        return new Shareable_CodeSystemProfile(resource);
    }

    static createResource (args: Shareable_CodeSystemProfileRaw) : CodeSystem {
        const resource = buildResource<CodeSystem>( {
            resourceType: "CodeSystem",
            url: args.url,
            version: args.version,
            name: args.name,
            status: args.status,
            experimental: args.experimental,
            publisher: args.publisher,
            description: args.description,
            concept: args.concept,
            content: args.content,
            meta: { profile: [Shareable_CodeSystemProfile.canonicalUrl] },
        })
        return resource;
    }

    static create (args: Shareable_CodeSystemProfileRaw) : Shareable_CodeSystemProfile {
        return Shareable_CodeSystemProfile.apply(Shareable_CodeSystemProfile.createResource(args));
    }

    toResource () : CodeSystem {
        return this.resource;
    }

    // Field accessors
    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    getVersion () : string | undefined {
        return this.resource.version as string | undefined;
    }

    setVersion (value: string) : this {
        Object.assign(this.resource, { version: value });
        return this;
    }

    getName () : string | undefined {
        return this.resource.name as string | undefined;
    }

    setName (value: string) : this {
        Object.assign(this.resource, { name: value });
        return this;
    }

    getStatus () : ("draft" | "active" | "retired" | "unknown") | undefined {
        return this.resource.status as ("draft" | "active" | "retired" | "unknown") | undefined;
    }

    setStatus (value: ("draft" | "active" | "retired" | "unknown")) : this {
        Object.assign(this.resource, { status: value });
        return this;
    }

    getExperimental () : boolean | undefined {
        return this.resource.experimental as boolean | undefined;
    }

    setExperimental (value: boolean) : this {
        Object.assign(this.resource, { experimental: value });
        return this;
    }

    getPublisher () : string | undefined {
        return this.resource.publisher as string | undefined;
    }

    setPublisher (value: string) : this {
        Object.assign(this.resource, { publisher: value });
        return this;
    }

    getDescription () : string | undefined {
        return this.resource.description as string | undefined;
    }

    setDescription (value: string) : this {
        Object.assign(this.resource, { description: value });
        return this;
    }

    getConcept () : CodeSystemConcept[] | undefined {
        return this.resource.concept as CodeSystemConcept[] | undefined;
    }

    setConcept (value: CodeSystemConcept[]) : this {
        Object.assign(this.resource, { concept: value });
        return this;
    }

    getContent () : ("not-present" | "example" | "fragment" | "complete" | "supplement") | undefined {
        return this.resource.content as ("not-present" | "example" | "fragment" | "complete" | "supplement") | undefined;
    }

    setContent (value: ("not-present" | "example" | "fragment" | "complete" | "supplement")) : this {
        Object.assign(this.resource, { content: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "Shareable CodeSystem"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateRequired(res, profileName, "version"),
                ...validateRequired(res, profileName, "name"),
                ...validateRequired(res, profileName, "status"),
                ...validateEnum(res, profileName, "status", ["draft","active","retired","unknown"]),
                ...validateRequired(res, profileName, "experimental"),
                ...validateRequired(res, profileName, "publisher"),
                ...validateRequired(res, profileName, "description"),
                ...validateRequired(res, profileName, "concept"),
            ],
            warnings: [],
        }
    }

}

