// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Composition } from "../../hl7-fhir-r4-core/Composition";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

import { versionNumberProfile } from "./Extension_versionNumber";

import {
    buildResource,
    ensureProfile,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type Clinical_DocumentProfileRaw = {
    status: ("preliminary" | "final" | "amended" | "entered-in-error");
    type: CodeableConcept;
    date: string;
    author: Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">[];
    title: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/clinicaldocument (pkg: hl7.fhir.r4.core#4.0.1)
export class Clinical_DocumentProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/clinicaldocument";

    private resource: Composition;

    constructor (resource: Composition) {
        this.resource = resource;
    }

    static from (resource: Composition) : Clinical_DocumentProfile {
        if (!resource.meta?.profile?.includes(Clinical_DocumentProfile.canonicalUrl)) {
            throw new Error(`Clinical_DocumentProfile: meta.profile must include ${Clinical_DocumentProfile.canonicalUrl}`)
        }
        const profile = new Clinical_DocumentProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Composition) : Clinical_DocumentProfile {
        ensureProfile(resource, Clinical_DocumentProfile.canonicalUrl);
        return new Clinical_DocumentProfile(resource);
    }

    static createResource (args: Clinical_DocumentProfileRaw) : Composition {
        const resource = buildResource<Composition>( {
            resourceType: "Composition",
            status: args.status,
            type: args.type,
            date: args.date,
            author: args.author,
            title: args.title,
            meta: { profile: [Clinical_DocumentProfile.canonicalUrl] },
        })
        return resource;
    }

    static create (args: Clinical_DocumentProfileRaw) : Clinical_DocumentProfile {
        return Clinical_DocumentProfile.apply(Clinical_DocumentProfile.createResource(args));
    }

    toResource () : Composition {
        return this.resource;
    }

    // Field accessors
    getStatus () : ("preliminary" | "final" | "amended" | "entered-in-error") | undefined {
        return this.resource.status as ("preliminary" | "final" | "amended" | "entered-in-error") | undefined;
    }

    setStatus (value: ("preliminary" | "final" | "amended" | "entered-in-error")) : this {
        Object.assign(this.resource, { status: value });
        return this;
    }

    getType () : CodeableConcept | undefined {
        return this.resource.type as CodeableConcept | undefined;
    }

    setType (value: CodeableConcept) : this {
        Object.assign(this.resource, { type: value });
        return this;
    }

    getDate () : string | undefined {
        return this.resource.date as string | undefined;
    }

    setDate (value: string) : this {
        Object.assign(this.resource, { date: value });
        return this;
    }

    getAuthor () : Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">[] | undefined {
        return this.resource.author as Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">[] | undefined;
    }

    setAuthor (value: Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">[]) : this {
        Object.assign(this.resource, { author: value });
        return this;
    }

    getTitle () : string | undefined {
        return this.resource.title as string | undefined;
    }

    setTitle (value: string) : this {
        Object.assign(this.resource, { title: value });
        return this;
    }

    // Extensions
    public setVersionNumber (value: versionNumberProfile | Extension | string): this {
        if (value instanceof versionNumberProfile) {
            pushExtension(this.resource, value.toResource())
        } else if (isExtension(value)) {
            if (value.url !== "http://hl7.org/fhir/StructureDefinition/composition-clinicaldocument-versionNumber") throw new Error(`Expected extension url 'http://hl7.org/fhir/StructureDefinition/composition-clinicaldocument-versionNumber', got '${value.url}'`)
            pushExtension(this.resource, value)
        } else {
            pushExtension(this.resource, versionNumberProfile.createResource({ valueString: value as string }))
        }
        return this
    }

    public getVersionNumber(mode: 'flat'): string | undefined;
    public getVersionNumber(mode: 'profile'): versionNumberProfile | undefined;
    public getVersionNumber(mode: 'raw'): Extension | undefined;
    public getVersionNumber(): string | undefined;
    public getVersionNumber (mode: 'flat' | 'profile' | 'raw' = 'flat'): string | versionNumberProfile | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/composition-clinicaldocument-versionNumber")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        if (mode === 'profile') return versionNumberProfile.apply(ext)
        return getExtensionValue<string>(ext, "valueString")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "Clinical Document"
        const res = this.resource
        return {
            errors: [
                ...validateReference(res, profileName, "subject", ["Device","Group","Location","Patient","Practitioner"]),
            ],
            warnings: [],
        }
    }

}

