// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { DiagnosticReport } from "../../hl7-fhir-r4-core/DiagnosticReport";

import {
    buildResource,
    ensureProfile,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type Example_Lipid_ProfileRaw = {
    status: ("registered" | "partial" | "preliminary" | "final" | "amended" | "corrected" | "appended" | "cancelled" | "entered-in-error" | "unknown");
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/lipidprofile (pkg: hl7.fhir.r4.core#4.0.1)
export class Example_Lipid_Profile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/lipidprofile";

    private resource: DiagnosticReport;

    constructor (resource: DiagnosticReport) {
        this.resource = resource;
    }

    static from (resource: DiagnosticReport) : Example_Lipid_Profile {
        if (!resource.meta?.profile?.includes(Example_Lipid_Profile.canonicalUrl)) {
            throw new Error(`Example_Lipid_Profile: meta.profile must include ${Example_Lipid_Profile.canonicalUrl}`)
        }
        const profile = new Example_Lipid_Profile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: DiagnosticReport) : Example_Lipid_Profile {
        ensureProfile(resource, Example_Lipid_Profile.canonicalUrl);
        return new Example_Lipid_Profile(resource);
    }

    static createResource (args: Example_Lipid_ProfileRaw) : DiagnosticReport {
        const resource = buildResource<DiagnosticReport>( {
            resourceType: "DiagnosticReport",
            code: {"coding":[{"system":"http://loinc.org","code":"57698-3","display":"Lipid panel with direct LDL - Serum or Plasma"}]},
            status: args.status,
            meta: { profile: [Example_Lipid_Profile.canonicalUrl] },
        })
        return resource;
    }

    static create (args: Example_Lipid_ProfileRaw) : Example_Lipid_Profile {
        return Example_Lipid_Profile.apply(Example_Lipid_Profile.createResource(args));
    }

    toResource () : DiagnosticReport {
        return this.resource;
    }

    // Field accessors
    getStatus () : ("registered" | "partial" | "preliminary" | "final" | "amended" | "corrected" | "appended" | "cancelled" | "entered-in-error" | "unknown") | undefined {
        return this.resource.status as ("registered" | "partial" | "preliminary" | "final" | "amended" | "corrected" | "appended" | "cancelled" | "entered-in-error" | "unknown") | undefined;
    }

    setStatus (value: ("registered" | "partial" | "preliminary" | "final" | "amended" | "corrected" | "appended" | "cancelled" | "entered-in-error" | "unknown")) : this {
        Object.assign(this.resource, { status: value });
        return this;
    }

    getCode () : CodeableConcept | undefined {
        return this.resource.code as CodeableConcept | undefined;
    }

    setCode (value: CodeableConcept) : this {
        Object.assign(this.resource, { code: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "Example Lipid Profile"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "code"),
                ...validateFixedValue(res, profileName, "code", {"coding":[{"system":"http://loinc.org","code":"57698-3","display":"Lipid panel with direct LDL - Serum or Plasma"}]}),
                ...validateReference(res, profileName, "result", ["Observation"]),
            ],
            warnings: [
                ...validateMustSupport(res, profileName, "conclusion"),
            ],
        }
    }

}

