// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type locationPerformedProfileRaw = {
    valueReference: Reference;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/diagnosticReport-locationPerformed (pkg: hl7.fhir.r4.core#4.0.1)
export class locationPerformedProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/diagnosticReport-locationPerformed";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : locationPerformedProfile {
        const profile = new locationPerformedProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : locationPerformedProfile {
        return new locationPerformedProfile(resource);
    }

    static createResource (args: locationPerformedProfileRaw) : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/diagnosticReport-locationPerformed",
            valueReference: args.valueReference,
        })
        return resource;
    }

    static create (args: locationPerformedProfileRaw) : locationPerformedProfile {
        return locationPerformedProfile.apply(locationPerformedProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueReference () : Reference | undefined {
        return this.resource.valueReference as Reference | undefined;
    }

    setValueReference (value: Reference) : this {
        Object.assign(this.resource, { valueReference: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "locationPerformed"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", locationPerformedProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueReference"]),
            ],
            warnings: [],
        }
    }

}

