// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    isRawExtensionInput,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type otherNameProfileRaw = {
    extension: Extension[];
}

export type otherNameProfileFlat = {
    name: string;
    preferred?: boolean;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/codesystem-otherName (pkg: hl7.fhir.r4.core#4.0.1)
export class otherNameProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/codesystem-otherName";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : otherNameProfile {
        const profile = new otherNameProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : otherNameProfile {
        return new otherNameProfile(resource);
    }

    private static resolveInput (args: otherNameProfileRaw | otherNameProfileFlat) : Extension[] {
        if (isRawExtensionInput<otherNameProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.name !== undefined) {
                result.push({ url: "name", valueString: args.name } as Extension);
            }
            if (args.preferred !== undefined) {
                result.push({ url: "preferred", valueBoolean: args.preferred } as Extension);
            }
            return result;
        }
    }

    static createResource (args: otherNameProfileRaw | otherNameProfileFlat) : Extension {
        const resolvedExtensions = otherNameProfile.resolveInput(args ?? {});

        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/codesystem-otherName",
            extension: resolvedExtensions,
        })
        return resource;
    }

    static create (args: otherNameProfileRaw | otherNameProfileFlat) : otherNameProfile {
        return otherNameProfile.apply(otherNameProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined;
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    public setName (value: string): this {
        pushExtension(this.resource, { url: "name", valueString: value } as Extension)
        return this
    }

    public getName(mode: 'flat'): string | undefined;
    public getName(mode: 'raw'): Extension | undefined;
    public getName(): string | undefined;
    public getName (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "name")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueString")
    }

    public setPreferred (value: boolean): this {
        pushExtension(this.resource, { url: "preferred", valueBoolean: value } as Extension)
        return this
    }

    public getPreferred(mode: 'flat'): boolean | undefined;
    public getPreferred(mode: 'raw'): Extension | undefined;
    public getPreferred(): boolean | undefined;
    public getPreferred (mode: 'flat' | 'raw' = 'flat'): boolean | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "preferred")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<boolean>(ext, "valueBoolean")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "otherName"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "extension"),
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", otherNameProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

