// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

import {
    buildResource,
    isRawExtensionInput,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type acceptanceProfileRaw = {
    extension: Extension[];
}

export type acceptanceProfileFlat = {
    individual: Reference;
    status?: string;
    priority?: CodeableConcept;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/goal-acceptance (pkg: hl7.fhir.r4.core#4.0.1)
export class acceptanceProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/goal-acceptance";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : acceptanceProfile {
        const profile = new acceptanceProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : acceptanceProfile {
        return new acceptanceProfile(resource);
    }

    private static resolveInput (args: acceptanceProfileRaw | acceptanceProfileFlat) : Extension[] {
        if (isRawExtensionInput<acceptanceProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.individual !== undefined) {
                result.push({ url: "individual", valueReference: args.individual } as Extension);
            }
            if (args.status !== undefined) {
                result.push({ url: "status", valueCode: args.status } as Extension);
            }
            if (args.priority !== undefined) {
                result.push({ url: "priority", valueCodeableConcept: args.priority } as Extension);
            }
            return result;
        }
    }

    static createResource (args: acceptanceProfileRaw | acceptanceProfileFlat) : Extension {
        const resolvedExtensions = acceptanceProfile.resolveInput(args ?? {});

        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/goal-acceptance",
            extension: resolvedExtensions,
        })
        return resource;
    }

    static create (args: acceptanceProfileRaw | acceptanceProfileFlat) : acceptanceProfile {
        return acceptanceProfile.apply(acceptanceProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined;
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    public setIndividual (value: Reference): this {
        pushExtension(this.resource, { url: "individual", valueReference: value } as Extension)
        return this
    }

    public getIndividual(mode: 'flat'): Reference | undefined;
    public getIndividual(mode: 'raw'): Extension | undefined;
    public getIndividual(): Reference | undefined;
    public getIndividual (mode: 'flat' | 'raw' = 'flat'): Reference | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "individual")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<Reference>(ext, "valueReference")
    }

    public setStatus (value: string): this {
        pushExtension(this.resource, { url: "status", valueCode: value } as Extension)
        return this
    }

    public getStatus(mode: 'flat'): string | undefined;
    public getStatus(mode: 'raw'): Extension | undefined;
    public getStatus(): string | undefined;
    public getStatus (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "status")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueCode")
    }

    public setPriority (value: CodeableConcept): this {
        pushExtension(this.resource, { url: "priority", valueCodeableConcept: value } as Extension)
        return this
    }

    public getPriority(mode: 'flat'): CodeableConcept | undefined;
    public getPriority(mode: 'raw'): Extension | undefined;
    public getPriority(): CodeableConcept | undefined;
    public getPriority (mode: 'flat' | 'raw' = 'flat'): CodeableConcept | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "priority")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<CodeableConcept>(ext, "valueCodeableConcept")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "acceptance"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "extension"),
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", acceptanceProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

