// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type mapProfileRaw = {
    valueCanonical: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/codesystem-map (pkg: hl7.fhir.r4.core#4.0.1)
export class mapProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/codesystem-map";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : mapProfile {
        const profile = new mapProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : mapProfile {
        return new mapProfile(resource);
    }

    static createResource (args: mapProfileRaw) : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/codesystem-map",
            valueCanonical: args.valueCanonical,
        })
        return resource;
    }

    static create (args: mapProfileRaw) : mapProfile {
        return mapProfile.apply(mapProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueCanonical () : string | undefined {
        return this.resource.valueCanonical as string | undefined;
    }

    setValueCanonical (value: string) : this {
        Object.assign(this.resource, { valueCanonical: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "map"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", mapProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueCanonical"]),
            ],
            warnings: [],
        }
    }

}

