// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type fmm_no_warningsProfileRaw = {
    valueInteger: number;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm-no-warnings (pkg: hl7.fhir.r4.core#4.0.1)
export class fmm_no_warningsProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm-no-warnings";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : fmm_no_warningsProfile {
        const profile = new fmm_no_warningsProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : fmm_no_warningsProfile {
        return new fmm_no_warningsProfile(resource);
    }

    static createResource (args: fmm_no_warningsProfileRaw) : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm-no-warnings",
            valueInteger: args.valueInteger,
        })
        return resource;
    }

    static create (args: fmm_no_warningsProfileRaw) : fmm_no_warningsProfile {
        return fmm_no_warningsProfile.apply(fmm_no_warningsProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueInteger () : number | undefined {
        return this.resource.valueInteger as number | undefined;
    }

    setValueInteger (value: number) : this {
        Object.assign(this.resource, { valueInteger: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "fmm-no-warnings"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", fmm_no_warningsProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueInteger"]),
            ],
            warnings: [],
        }
    }

}

