// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Attachment } from "../../hl7-fhir-r4-core/Attachment";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type mediaProfileRaw = {
    valueAttachment: Attachment;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/communication-media (pkg: hl7.fhir.r4.core#4.0.1)
export class mediaProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/communication-media";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : mediaProfile {
        const profile = new mediaProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : mediaProfile {
        return new mediaProfile(resource);
    }

    static createResource (args: mediaProfileRaw) : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/communication-media",
            valueAttachment: args.valueAttachment,
        })
        return resource;
    }

    static create (args: mediaProfileRaw) : mediaProfile {
        return mediaProfile.apply(mediaProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueAttachment () : Attachment | undefined {
        return this.resource.valueAttachment as Attachment | undefined;
    }

    setValueAttachment (value: Attachment) : this {
        Object.assign(this.resource, { valueAttachment: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "media"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", mediaProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueAttachment"]),
            ],
            warnings: [],
        }
    }

}

