// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type secondaryFindingProfileRaw = {
    valueCodeableConcept: CodeableConcept;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/observation-secondaryFinding (pkg: hl7.fhir.r4.core#4.0.1)
export class secondaryFindingProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/observation-secondaryFinding";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : secondaryFindingProfile {
        const profile = new secondaryFindingProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : secondaryFindingProfile {
        return new secondaryFindingProfile(resource);
    }

    static createResource (args: secondaryFindingProfileRaw) : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/observation-secondaryFinding",
            valueCodeableConcept: args.valueCodeableConcept,
        })
        return resource;
    }

    static create (args: secondaryFindingProfileRaw) : secondaryFindingProfile {
        return secondaryFindingProfile.apply(secondaryFindingProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueCodeableConcept () : CodeableConcept | undefined {
        return this.resource.valueCodeableConcept as CodeableConcept | undefined;
    }

    setValueCodeableConcept (value: CodeableConcept) : this {
        Object.assign(this.resource, { valueCodeableConcept: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "secondaryFinding"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", secondaryFindingProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueCodeableConcept"]),
            ],
            warnings: [],
        }
    }

}

