// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type incisionDateTimeProfileRaw = {
    valueDateTime: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/procedure-incisionDateTime (pkg: hl7.fhir.r4.core#4.0.1)
export class incisionDateTimeProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/procedure-incisionDateTime";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : incisionDateTimeProfile {
        const profile = new incisionDateTimeProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : incisionDateTimeProfile {
        return new incisionDateTimeProfile(resource);
    }

    static createResource (args: incisionDateTimeProfileRaw) : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/procedure-incisionDateTime",
            valueDateTime: args.valueDateTime,
        })
        return resource;
    }

    static create (args: incisionDateTimeProfileRaw) : incisionDateTimeProfile {
        return incisionDateTimeProfile.apply(incisionDateTimeProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueDateTime () : string | undefined {
        return this.resource.valueDateTime as string | undefined;
    }

    setValueDateTime (value: string) : this {
        Object.assign(this.resource, { valueDateTime: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "incisionDateTime"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", incisionDateTimeProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueDateTime"]),
            ],
            warnings: [],
        }
    }

}

