// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type toocostlyProfileRaw = {
    valueBoolean: boolean;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/valueset-toocostly (pkg: hl7.fhir.r4.core#4.0.1)
export class toocostlyProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/valueset-toocostly";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : toocostlyProfile {
        const profile = new toocostlyProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : toocostlyProfile {
        return new toocostlyProfile(resource);
    }

    static createResource (args: toocostlyProfileRaw) : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/valueset-toocostly",
            valueBoolean: args.valueBoolean,
        })
        return resource;
    }

    static create (args: toocostlyProfileRaw) : toocostlyProfile {
        return toocostlyProfile.apply(toocostlyProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueBoolean () : boolean | undefined {
        return this.resource.valueBoolean as boolean | undefined;
    }

    setValueBoolean (value: boolean) : this {
        Object.assign(this.resource, { valueBoolean: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "toocostly"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", toocostlyProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueBoolean"]),
            ],
            warnings: [],
        }
    }

}

