// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

import {
    buildResource,
    isRawExtensionInput,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type ItemProfileRaw = {
    extension: Extension[];
}

export type ItemProfileFlat = {
    code: CodeableConcept;
    geneticsObservation?: Reference;
    specimen?: Reference;
    status?: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/servicerequest-geneticsItem (pkg: hl7.fhir.r4.core#4.0.1)
export class ItemProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/servicerequest-geneticsItem";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : ItemProfile {
        const profile = new ItemProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : ItemProfile {
        return new ItemProfile(resource);
    }

    private static resolveInput (args: ItemProfileRaw | ItemProfileFlat) : Extension[] {
        if (isRawExtensionInput<ItemProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.code !== undefined) {
                result.push({ url: "code", valueCodeableConcept: args.code } as Extension);
            }
            if (args.geneticsObservation !== undefined) {
                result.push({ url: "geneticsObservation", valueReference: args.geneticsObservation } as Extension);
            }
            if (args.specimen !== undefined) {
                result.push({ url: "specimen", valueReference: args.specimen } as Extension);
            }
            if (args.status !== undefined) {
                result.push({ url: "status", valueCode: args.status } as Extension);
            }
            return result;
        }
    }

    static createResource (args: ItemProfileRaw | ItemProfileFlat) : Extension {
        const resolvedExtensions = ItemProfile.resolveInput(args ?? {});

        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/servicerequest-geneticsItem",
            extension: resolvedExtensions,
        })
        return resource;
    }

    static create (args: ItemProfileRaw | ItemProfileFlat) : ItemProfile {
        return ItemProfile.apply(ItemProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined;
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    public setCode (value: CodeableConcept): this {
        pushExtension(this.resource, { url: "code", valueCodeableConcept: value } as Extension)
        return this
    }

    public getCode(mode: 'flat'): CodeableConcept | undefined;
    public getCode(mode: 'raw'): Extension | undefined;
    public getCode(): CodeableConcept | undefined;
    public getCode (mode: 'flat' | 'raw' = 'flat'): CodeableConcept | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "code")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<CodeableConcept>(ext, "valueCodeableConcept")
    }

    public setGeneticsObservation (value: Reference): this {
        pushExtension(this.resource, { url: "geneticsObservation", valueReference: value } as Extension)
        return this
    }

    public getGeneticsObservation(mode: 'flat'): Reference | undefined;
    public getGeneticsObservation(mode: 'raw'): Extension | undefined;
    public getGeneticsObservation(): Reference | undefined;
    public getGeneticsObservation (mode: 'flat' | 'raw' = 'flat'): Reference | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "geneticsObservation")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<Reference>(ext, "valueReference")
    }

    public setSpecimen (value: Reference): this {
        pushExtension(this.resource, { url: "specimen", valueReference: value } as Extension)
        return this
    }

    public getSpecimen(mode: 'flat'): Reference | undefined;
    public getSpecimen(mode: 'raw'): Extension | undefined;
    public getSpecimen(): Reference | undefined;
    public getSpecimen (mode: 'flat' | 'raw' = 'flat'): Reference | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "specimen")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<Reference>(ext, "valueReference")
    }

    public setStatus (value: string): this {
        pushExtension(this.resource, { url: "status", valueCode: value } as Extension)
        return this
    }

    public getStatus(mode: 'flat'): string | undefined;
    public getStatus(mode: 'raw'): Extension | undefined;
    public getStatus(): string | undefined;
    public getStatus (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "status")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueCode")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "Item"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "extension"),
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", ItemProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

