// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type referenceFilterProfileRaw = {
    valueString: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/questionnaire-referenceFilter (pkg: hl7.fhir.r4.core#4.0.1)
export class referenceFilterProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/questionnaire-referenceFilter";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : referenceFilterProfile {
        const profile = new referenceFilterProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : referenceFilterProfile {
        return new referenceFilterProfile(resource);
    }

    static createResource (args: referenceFilterProfileRaw) : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/questionnaire-referenceFilter",
            valueString: args.valueString,
        })
        return resource;
    }

    static create (args: referenceFilterProfileRaw) : referenceFilterProfile {
        return referenceFilterProfile.apply(referenceFilterProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueString () : string | undefined {
        return this.resource.valueString as string | undefined;
    }

    setValueString (value: string) : this {
        Object.assign(this.resource, { valueString: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "referenceFilter"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", referenceFilterProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueString"]),
            ],
            warnings: [],
        }
    }

}

