// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    isRawExtensionInput,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type AlleleProfileRaw = {
    extension?: Extension[];
}

export type AlleleProfileFlat = {
    name?: CodeableConcept;
    state?: CodeableConcept;
    frequency?: number;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/observation-geneticsAllele (pkg: hl7.fhir.r4.core#4.0.1)
export class AlleleProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/observation-geneticsAllele";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : AlleleProfile {
        const profile = new AlleleProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : AlleleProfile {
        return new AlleleProfile(resource);
    }

    private static resolveInput (args: AlleleProfileRaw | AlleleProfileFlat) : Extension[] {
        if (isRawExtensionInput<AlleleProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.name !== undefined) {
                result.push({ url: "Name", valueCodeableConcept: args.name } as Extension);
            }
            if (args.state !== undefined) {
                result.push({ url: "State", valueCodeableConcept: args.state } as Extension);
            }
            if (args.frequency !== undefined) {
                result.push({ url: "Frequency", valueDecimal: args.frequency } as Extension);
            }
            return result;
        }
    }

    static createResource (args?: AlleleProfileRaw | AlleleProfileFlat) : Extension {
        const resolvedExtensions = AlleleProfile.resolveInput(args ?? {});

        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/observation-geneticsAllele",
            extension: resolvedExtensions,
        })
        return resource;
    }

    static create (args?: AlleleProfileRaw | AlleleProfileFlat) : AlleleProfile {
        return AlleleProfile.apply(AlleleProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    public setName (value: CodeableConcept): this {
        pushExtension(this.resource, { url: "Name", valueCodeableConcept: value } as Extension)
        return this
    }

    public getName(mode: 'flat'): CodeableConcept | undefined;
    public getName(mode: 'raw'): Extension | undefined;
    public getName(): CodeableConcept | undefined;
    public getName (mode: 'flat' | 'raw' = 'flat'): CodeableConcept | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "Name")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<CodeableConcept>(ext, "valueCodeableConcept")
    }

    public setState (value: CodeableConcept): this {
        pushExtension(this.resource, { url: "State", valueCodeableConcept: value } as Extension)
        return this
    }

    public getState(mode: 'flat'): CodeableConcept | undefined;
    public getState(mode: 'raw'): Extension | undefined;
    public getState(): CodeableConcept | undefined;
    public getState (mode: 'flat' | 'raw' = 'flat'): CodeableConcept | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "State")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<CodeableConcept>(ext, "valueCodeableConcept")
    }

    public setFrequency (value: number): this {
        pushExtension(this.resource, { url: "Frequency", valueDecimal: value } as Extension)
        return this
    }

    public getFrequency(mode: 'flat'): number | undefined;
    public getFrequency(mode: 'raw'): Extension | undefined;
    public getFrequency(): number | undefined;
    public getFrequency (mode: 'flat' | 'raw' = 'flat'): number | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "Frequency")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<number>(ext, "valueDecimal")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "Allele"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", AlleleProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

