// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type permitted_value_conceptmapProfileRaw = {
    valueCanonical: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/11179-permitted-value-conceptmap (pkg: hl7.fhir.r4.core#4.0.1)
export class permitted_value_conceptmapProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/11179-permitted-value-conceptmap";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : permitted_value_conceptmapProfile {
        const profile = new permitted_value_conceptmapProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : permitted_value_conceptmapProfile {
        return new permitted_value_conceptmapProfile(resource);
    }

    static createResource (args: permitted_value_conceptmapProfileRaw) : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/11179-permitted-value-conceptmap",
            valueCanonical: args.valueCanonical,
        })
        return resource;
    }

    static create (args: permitted_value_conceptmapProfileRaw) : permitted_value_conceptmapProfile {
        return permitted_value_conceptmapProfile.apply(permitted_value_conceptmapProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueCanonical () : string | undefined {
        return this.resource.valueCanonical as string | undefined;
    }

    setValueCanonical (value: string) : this {
        Object.assign(this.resource, { valueCanonical: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "permitted-value-conceptmap"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", permitted_value_conceptmapProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueCanonical"]),
            ],
            warnings: [],
        }
    }

}

