// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    isRawExtensionInput,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type animalProfileRaw = {
    extension: Extension[];
}

export type animalProfileFlat = {
    species: CodeableConcept;
    breed?: CodeableConcept;
    genderStatus?: CodeableConcept;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/patient-animal (pkg: hl7.fhir.r4.core#4.0.1)
export class animalProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/patient-animal";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : animalProfile {
        const profile = new animalProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : animalProfile {
        return new animalProfile(resource);
    }

    private static resolveInput (args: animalProfileRaw | animalProfileFlat) : Extension[] {
        if (isRawExtensionInput<animalProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.species !== undefined) {
                result.push({ url: "species", valueCodeableConcept: args.species } as Extension);
            }
            if (args.breed !== undefined) {
                result.push({ url: "breed", valueCodeableConcept: args.breed } as Extension);
            }
            if (args.genderStatus !== undefined) {
                result.push({ url: "genderStatus", valueCodeableConcept: args.genderStatus } as Extension);
            }
            return result;
        }
    }

    static createResource (args: animalProfileRaw | animalProfileFlat) : Extension {
        const resolvedExtensions = animalProfile.resolveInput(args ?? {});

        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/patient-animal",
            extension: resolvedExtensions,
        })
        return resource;
    }

    static create (args: animalProfileRaw | animalProfileFlat) : animalProfile {
        return animalProfile.apply(animalProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined;
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    public setSpecies (value: CodeableConcept): this {
        pushExtension(this.resource, { url: "species", valueCodeableConcept: value } as Extension)
        return this
    }

    public getSpecies(mode: 'flat'): CodeableConcept | undefined;
    public getSpecies(mode: 'raw'): Extension | undefined;
    public getSpecies(): CodeableConcept | undefined;
    public getSpecies (mode: 'flat' | 'raw' = 'flat'): CodeableConcept | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "species")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<CodeableConcept>(ext, "valueCodeableConcept")
    }

    public setBreed (value: CodeableConcept): this {
        pushExtension(this.resource, { url: "breed", valueCodeableConcept: value } as Extension)
        return this
    }

    public getBreed(mode: 'flat'): CodeableConcept | undefined;
    public getBreed(mode: 'raw'): Extension | undefined;
    public getBreed(): CodeableConcept | undefined;
    public getBreed (mode: 'flat' | 'raw' = 'flat'): CodeableConcept | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "breed")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<CodeableConcept>(ext, "valueCodeableConcept")
    }

    public setGenderStatus (value: CodeableConcept): this {
        pushExtension(this.resource, { url: "genderStatus", valueCodeableConcept: value } as Extension)
        return this
    }

    public getGenderStatus(mode: 'flat'): CodeableConcept | undefined;
    public getGenderStatus(mode: 'raw'): Extension | undefined;
    public getGenderStatus(): CodeableConcept | undefined;
    public getGenderStatus (mode: 'flat' | 'raw' = 'flat'): CodeableConcept | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "genderStatus")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<CodeableConcept>(ext, "valueCodeableConcept")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "animal"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "extension"),
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", animalProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

