// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    isRawExtensionInput,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type substanceExposureRiskProfileRaw = {
    extension: Extension[];
}

export type substanceExposureRiskProfileFlat = {
    substance: CodeableConcept;
    exposureRisk: CodeableConcept;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/allergyintolerance-substanceExposureRisk (pkg: hl7.fhir.r4.core#4.0.1)
export class substanceExposureRiskProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/allergyintolerance-substanceExposureRisk";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : substanceExposureRiskProfile {
        const profile = new substanceExposureRiskProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : substanceExposureRiskProfile {
        return new substanceExposureRiskProfile(resource);
    }

    private static resolveInput (args: substanceExposureRiskProfileRaw | substanceExposureRiskProfileFlat) : Extension[] {
        if (isRawExtensionInput<substanceExposureRiskProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.substance !== undefined) {
                result.push({ url: "substance", valueCodeableConcept: args.substance } as Extension);
            }
            if (args.exposureRisk !== undefined) {
                result.push({ url: "exposureRisk", valueCodeableConcept: args.exposureRisk } as Extension);
            }
            return result;
        }
    }

    static createResource (args: substanceExposureRiskProfileRaw | substanceExposureRiskProfileFlat) : Extension {
        const resolvedExtensions = substanceExposureRiskProfile.resolveInput(args ?? {});

        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/allergyintolerance-substanceExposureRisk",
            extension: resolvedExtensions,
        })
        return resource;
    }

    static create (args: substanceExposureRiskProfileRaw | substanceExposureRiskProfileFlat) : substanceExposureRiskProfile {
        return substanceExposureRiskProfile.apply(substanceExposureRiskProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined;
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    public setSubstance (value: CodeableConcept): this {
        pushExtension(this.resource, { url: "substance", valueCodeableConcept: value } as Extension)
        return this
    }

    public getSubstance(mode: 'flat'): CodeableConcept | undefined;
    public getSubstance(mode: 'raw'): Extension | undefined;
    public getSubstance(): CodeableConcept | undefined;
    public getSubstance (mode: 'flat' | 'raw' = 'flat'): CodeableConcept | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "substance")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<CodeableConcept>(ext, "valueCodeableConcept")
    }

    public setExposureRisk (value: CodeableConcept): this {
        pushExtension(this.resource, { url: "exposureRisk", valueCodeableConcept: value } as Extension)
        return this
    }

    public getExposureRisk(mode: 'flat'): CodeableConcept | undefined;
    public getExposureRisk(mode: 'raw'): Extension | undefined;
    public getExposureRisk(): CodeableConcept | undefined;
    public getExposureRisk (mode: 'flat' | 'raw' = 'flat'): CodeableConcept | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "exposureRisk")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<CodeableConcept>(ext, "valueCodeableConcept")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "substanceExposureRisk"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "extension"),
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", substanceExposureRiskProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

