// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type capabilitiesProfileRaw = {
    valueCode: string;
}

// CanonicalURL: http://fhir-registry.smarthealthit.org/StructureDefinition/capabilities (pkg: hl7.fhir.r4.core#4.0.1)
export class capabilitiesProfile {
    static readonly canonicalUrl = "http://fhir-registry.smarthealthit.org/StructureDefinition/capabilities";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : capabilitiesProfile {
        const profile = new capabilitiesProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : capabilitiesProfile {
        return new capabilitiesProfile(resource);
    }

    static createResource (args: capabilitiesProfileRaw) : Extension {
        const resource = buildResource<Extension>( {
            url: "http://fhir-registry.smarthealthit.org/StructureDefinition/capabilities",
            valueCode: args.valueCode,
        })
        return resource;
    }

    static create (args: capabilitiesProfileRaw) : capabilitiesProfile {
        return capabilitiesProfile.apply(capabilitiesProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueCode () : string | undefined {
        return this.resource.valueCode as string | undefined;
    }

    setValueCode (value: string) : this {
        Object.assign(this.resource, { valueCode: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "capabilities"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", capabilitiesProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueCode"]),
            ],
            warnings: [],
        }
    }

}

