// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    isRawExtensionInput,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type measureInfoProfileRaw = {
    extension?: Extension[];
}

export type measureInfoProfileFlat = {
    measure?: string;
    groupId?: string;
    populationId?: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/cqf-measureInfo (pkg: hl7.fhir.r4.core#4.0.1)
export class measureInfoProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/cqf-measureInfo";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : measureInfoProfile {
        const profile = new measureInfoProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : measureInfoProfile {
        return new measureInfoProfile(resource);
    }

    private static resolveInput (args: measureInfoProfileRaw | measureInfoProfileFlat) : Extension[] {
        if (isRawExtensionInput<measureInfoProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.measure !== undefined) {
                result.push({ url: "measure", valueCanonical: args.measure } as Extension);
            }
            if (args.groupId !== undefined) {
                result.push({ url: "groupId", valueString: args.groupId } as Extension);
            }
            if (args.populationId !== undefined) {
                result.push({ url: "populationId", valueString: args.populationId } as Extension);
            }
            return result;
        }
    }

    static createResource (args?: measureInfoProfileRaw | measureInfoProfileFlat) : Extension {
        const resolvedExtensions = measureInfoProfile.resolveInput(args ?? {});

        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/cqf-measureInfo",
            extension: resolvedExtensions,
        })
        return resource;
    }

    static create (args?: measureInfoProfileRaw | measureInfoProfileFlat) : measureInfoProfile {
        return measureInfoProfile.apply(measureInfoProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    public setMeasure (value: string): this {
        pushExtension(this.resource, { url: "measure", valueCanonical: value } as Extension)
        return this
    }

    public getMeasure(mode: 'flat'): string | undefined;
    public getMeasure(mode: 'raw'): Extension | undefined;
    public getMeasure(): string | undefined;
    public getMeasure (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "measure")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueCanonical")
    }

    public setGroupId (value: string): this {
        pushExtension(this.resource, { url: "groupId", valueString: value } as Extension)
        return this
    }

    public getGroupId(mode: 'flat'): string | undefined;
    public getGroupId(mode: 'raw'): Extension | undefined;
    public getGroupId(): string | undefined;
    public getGroupId (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "groupId")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueString")
    }

    public setPopulationId (value: string): this {
        pushExtension(this.resource, { url: "populationId", valueString: value } as Extension)
        return this
    }

    public getPopulationId(mode: 'flat'): string | undefined;
    public getPopulationId(mode: 'raw'): Extension | undefined;
    public getPopulationId(): string | undefined;
    public getPopulationId (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "populationId")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueString")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "measureInfo"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", measureInfoProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

