// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type cdsHooksEndpointProfileRaw = {
    valueUri: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/cqf-cdsHooksEndpoint (pkg: hl7.fhir.r4.core#4.0.1)
export class cdsHooksEndpointProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/cqf-cdsHooksEndpoint";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : cdsHooksEndpointProfile {
        const profile = new cdsHooksEndpointProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : cdsHooksEndpointProfile {
        return new cdsHooksEndpointProfile(resource);
    }

    static createResource (args: cdsHooksEndpointProfileRaw) : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/cqf-cdsHooksEndpoint",
            valueUri: args.valueUri,
        })
        return resource;
    }

    static create (args: cdsHooksEndpointProfileRaw) : cdsHooksEndpointProfile {
        return cdsHooksEndpointProfile.apply(cdsHooksEndpointProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueUri () : string | undefined {
        return this.resource.valueUri as string | undefined;
    }

    setValueUri (value: string) : this {
        Object.assign(this.resource, { valueUri: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "cdsHooksEndpoint"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", cdsHooksEndpointProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueUri"]),
            ],
            warnings: [],
        }
    }

}

