// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Identifier } from "../../hl7-fhir-r4-core/Identifier";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type ParticipantObjectContainsStudyProfileRaw = {
    valueIdentifier: Identifier;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/auditevent-ParticipantObjectContainsStudy (pkg: hl7.fhir.r4.core#4.0.1)
export class ParticipantObjectContainsStudyProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/auditevent-ParticipantObjectContainsStudy";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : ParticipantObjectContainsStudyProfile {
        const profile = new ParticipantObjectContainsStudyProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : ParticipantObjectContainsStudyProfile {
        return new ParticipantObjectContainsStudyProfile(resource);
    }

    static createResource (args: ParticipantObjectContainsStudyProfileRaw) : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/auditevent-ParticipantObjectContainsStudy",
            valueIdentifier: args.valueIdentifier,
        })
        return resource;
    }

    static create (args: ParticipantObjectContainsStudyProfileRaw) : ParticipantObjectContainsStudyProfile {
        return ParticipantObjectContainsStudyProfile.apply(ParticipantObjectContainsStudyProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueIdentifier () : Identifier | undefined {
        return this.resource.valueIdentifier as Identifier | undefined;
    }

    setValueIdentifier (value: Identifier) : this {
        Object.assign(this.resource, { valueIdentifier: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "ParticipantObjectContainsStudy"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", ParticipantObjectContainsStudyProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueIdentifier"]),
            ],
            warnings: [],
        }
    }

}

