// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Age } from "../../hl7-fhir-r4-core/Age";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/familymemberhistory-abatement (pkg: hl7.fhir.r4.core#4.0.1)
export class abatementProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/familymemberhistory-abatement";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : abatementProfile {
        const profile = new abatementProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : abatementProfile {
        return new abatementProfile(resource);
    }

    static createResource () : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/familymemberhistory-abatement",
        })
        return resource;
    }

    static create () : abatementProfile {
        return abatementProfile.apply(abatementProfile.createResource());
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    getValueDate () : string | undefined {
        return this.resource.valueDate as string | undefined;
    }

    setValueDate (value: string) : this {
        Object.assign(this.resource, { valueDate: value });
        return this;
    }

    getValueAge () : Age | undefined {
        return this.resource.valueAge as Age | undefined;
    }

    setValueAge (value: Age) : this {
        Object.assign(this.resource, { valueAge: value });
        return this;
    }

    getValueBoolean () : boolean | undefined {
        return this.resource.valueBoolean as boolean | undefined;
    }

    setValueBoolean (value: boolean) : this {
        Object.assign(this.resource, { valueBoolean: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "abatement"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", abatementProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueDate","valueAge","valueBoolean"]),
            ],
            warnings: [],
        }
    }

}

