// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type warningProfileRaw = {
    valueMarkdown: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/codesystem-warning (pkg: hl7.fhir.r4.core#4.0.1)
export class warningProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/codesystem-warning";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : warningProfile {
        const profile = new warningProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : warningProfile {
        return new warningProfile(resource);
    }

    static createResource (args: warningProfileRaw) : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/codesystem-warning",
            valueMarkdown: args.valueMarkdown,
        })
        return resource;
    }

    static create (args: warningProfileRaw) : warningProfile {
        return warningProfile.apply(warningProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueMarkdown () : string | undefined {
        return this.resource.valueMarkdown as string | undefined;
    }

    setValueMarkdown (value: string) : this {
        Object.assign(this.resource, { valueMarkdown: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "warning"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", warningProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueMarkdown"]),
            ],
            warnings: [],
        }
    }

}

