// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    isRawExtensionInput,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type constraintProfileRaw = {
    extension: Extension[];
}

export type constraintProfileFlat = {
    key: string;
    requirements?: string;
    severity: string;
    expression: string;
    human: string;
    location?: string[];
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/questionnaire-constraint (pkg: hl7.fhir.r4.core#4.0.1)
export class constraintProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/questionnaire-constraint";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : constraintProfile {
        const profile = new constraintProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : constraintProfile {
        return new constraintProfile(resource);
    }

    private static resolveInput (args: constraintProfileRaw | constraintProfileFlat) : Extension[] {
        if (isRawExtensionInput<constraintProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.key !== undefined) {
                result.push({ url: "key", valueId: args.key } as Extension);
            }
            if (args.requirements !== undefined) {
                result.push({ url: "requirements", valueString: args.requirements } as Extension);
            }
            if (args.severity !== undefined) {
                result.push({ url: "severity", valueCode: args.severity } as Extension);
            }
            if (args.expression !== undefined) {
                result.push({ url: "expression", valueString: args.expression } as Extension);
            }
            if (args.human !== undefined) {
                result.push({ url: "human", valueString: args.human } as Extension);
            }
            if (args.location) {
                for (const item of args.location) {
                    result.push({ url: "location", valueString: item } as Extension);
                }
            }
            return result;
        }
    }

    static createResource (args: constraintProfileRaw | constraintProfileFlat) : Extension {
        const resolvedExtensions = constraintProfile.resolveInput(args ?? {});

        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/questionnaire-constraint",
            extension: resolvedExtensions,
        })
        return resource;
    }

    static create (args: constraintProfileRaw | constraintProfileFlat) : constraintProfile {
        return constraintProfile.apply(constraintProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined;
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    public setKey (value: string): this {
        pushExtension(this.resource, { url: "key", valueId: value } as Extension)
        return this
    }

    public getKey(mode: 'flat'): string | undefined;
    public getKey(mode: 'raw'): Extension | undefined;
    public getKey(): string | undefined;
    public getKey (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "key")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueId")
    }

    public setRequirements (value: string): this {
        pushExtension(this.resource, { url: "requirements", valueString: value } as Extension)
        return this
    }

    public getRequirements(mode: 'flat'): string | undefined;
    public getRequirements(mode: 'raw'): Extension | undefined;
    public getRequirements(): string | undefined;
    public getRequirements (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "requirements")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueString")
    }

    public setSeverity (value: string): this {
        pushExtension(this.resource, { url: "severity", valueCode: value } as Extension)
        return this
    }

    public getSeverity(mode: 'flat'): string | undefined;
    public getSeverity(mode: 'raw'): Extension | undefined;
    public getSeverity(): string | undefined;
    public getSeverity (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "severity")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueCode")
    }

    public setExpression (value: string): this {
        pushExtension(this.resource, { url: "expression", valueString: value } as Extension)
        return this
    }

    public getExpression(mode: 'flat'): string | undefined;
    public getExpression(mode: 'raw'): Extension | undefined;
    public getExpression(): string | undefined;
    public getExpression (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "expression")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueString")
    }

    public setHuman (value: string): this {
        pushExtension(this.resource, { url: "human", valueString: value } as Extension)
        return this
    }

    public getHuman(mode: 'flat'): string | undefined;
    public getHuman(mode: 'raw'): Extension | undefined;
    public getHuman(): string | undefined;
    public getHuman (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "human")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueString")
    }

    public setLocation (value: string): this {
        pushExtension(this.resource, { url: "location", valueString: value } as Extension)
        return this
    }

    public getLocation(mode: 'flat'): string | undefined;
    public getLocation(mode: 'raw'): Extension | undefined;
    public getLocation(): string | undefined;
    public getLocation (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "location")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueString")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "constraint"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "extension"),
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", constraintProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

