// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    isRawExtensionInput,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type GeolocationProfileRaw = {
    extension: Extension[];
}

export type GeolocationProfileFlat = {
    latitude: number;
    longitude: number;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/geolocation (pkg: hl7.fhir.r4.core#4.0.1)
export class GeolocationProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/geolocation";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : GeolocationProfile {
        const profile = new GeolocationProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : GeolocationProfile {
        return new GeolocationProfile(resource);
    }

    private static resolveInput (args: GeolocationProfileRaw | GeolocationProfileFlat) : Extension[] {
        if (isRawExtensionInput<GeolocationProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.latitude !== undefined) {
                result.push({ url: "latitude", valueDecimal: args.latitude } as Extension);
            }
            if (args.longitude !== undefined) {
                result.push({ url: "longitude", valueDecimal: args.longitude } as Extension);
            }
            return result;
        }
    }

    static createResource (args: GeolocationProfileRaw | GeolocationProfileFlat) : Extension {
        const resolvedExtensions = GeolocationProfile.resolveInput(args ?? {});

        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/geolocation",
            extension: resolvedExtensions,
        })
        return resource;
    }

    static create (args: GeolocationProfileRaw | GeolocationProfileFlat) : GeolocationProfile {
        return GeolocationProfile.apply(GeolocationProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined;
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    public setLatitude (value: number): this {
        pushExtension(this.resource, { url: "latitude", valueDecimal: value } as Extension)
        return this
    }

    public getLatitude(mode: 'flat'): number | undefined;
    public getLatitude(mode: 'raw'): Extension | undefined;
    public getLatitude(): number | undefined;
    public getLatitude (mode: 'flat' | 'raw' = 'flat'): number | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "latitude")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<number>(ext, "valueDecimal")
    }

    public setLongitude (value: number): this {
        pushExtension(this.resource, { url: "longitude", valueDecimal: value } as Extension)
        return this
    }

    public getLongitude(mode: 'flat'): number | undefined;
    public getLongitude(mode: 'raw'): Extension | undefined;
    public getLongitude(): number | undefined;
    public getLongitude (mode: 'flat' | 'raw' = 'flat'): number | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "longitude")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<number>(ext, "valueDecimal")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "Geolocation"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "extension"),
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", GeolocationProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

