// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    isRawExtensionInput,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type historyProfileRaw = {
    extension?: Extension[];
}

export type historyProfileFlat = {
    name?: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/codesystem-history (pkg: hl7.fhir.r4.core#4.0.1)
export class historyProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/codesystem-history";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : historyProfile {
        const profile = new historyProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : historyProfile {
        return new historyProfile(resource);
    }

    private static resolveInput (args: historyProfileRaw | historyProfileFlat) : Extension[] {
        if (isRawExtensionInput<historyProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.name !== undefined) {
                result.push({ url: "name", valueString: args.name } as Extension);
            }
            return result;
        }
    }

    static createResource (args?: historyProfileRaw | historyProfileFlat) : Extension {
        const resolvedExtensions = historyProfile.resolveInput(args ?? {});

        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/codesystem-history",
            extension: resolvedExtensions,
        })
        return resource;
    }

    static create (args?: historyProfileRaw | historyProfileFlat) : historyProfile {
        return historyProfile.apply(historyProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    public setName (value: string): this {
        pushExtension(this.resource, { url: "name", valueString: value } as Extension)
        return this
    }

    public getName(mode: 'flat'): string | undefined;
    public getName(mode: 'raw'): Extension | undefined;
    public getName(): string | undefined;
    public getName (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "name")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueString")
    }

    public setRevision (value: Omit<Extension, "url"> | Extension): this {
        if (isExtension(value)) {
            if (value.url !== "revision") throw new Error(`Expected extension url 'revision', got '${value.url}'`)
            pushExtension(this.resource, value)
        } else {
            pushExtension(this.resource, { url: "revision", ...value } as Extension)
        }
        return this
    }

    public getRevision (): Extension | undefined {
        return this.resource.extension?.find(e => e.url === "revision")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "history"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", historyProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

