// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    isRawExtensionInput,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type oauth_urisProfileRaw = {
    extension: Extension[];
}

export type oauth_urisProfileFlat = {
    authorize: string;
    token: string;
    register?: string;
    manage?: string;
}

// CanonicalURL: http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris (pkg: hl7.fhir.r4.core#4.0.1)
export class oauth_urisProfile {
    static readonly canonicalUrl = "http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : oauth_urisProfile {
        const profile = new oauth_urisProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : oauth_urisProfile {
        return new oauth_urisProfile(resource);
    }

    private static resolveInput (args: oauth_urisProfileRaw | oauth_urisProfileFlat) : Extension[] {
        if (isRawExtensionInput<oauth_urisProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.authorize !== undefined) {
                result.push({ url: "authorize", valueUri: args.authorize } as Extension);
            }
            if (args.token !== undefined) {
                result.push({ url: "token", valueUri: args.token } as Extension);
            }
            if (args.register !== undefined) {
                result.push({ url: "register", valueUri: args.register } as Extension);
            }
            if (args.manage !== undefined) {
                result.push({ url: "manage", valueUri: args.manage } as Extension);
            }
            return result;
        }
    }

    static createResource (args: oauth_urisProfileRaw | oauth_urisProfileFlat) : Extension {
        const resolvedExtensions = oauth_urisProfile.resolveInput(args ?? {});

        const resource = buildResource<Extension>( {
            url: "http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris",
            extension: resolvedExtensions,
        })
        return resource;
    }

    static create (args: oauth_urisProfileRaw | oauth_urisProfileFlat) : oauth_urisProfile {
        return oauth_urisProfile.apply(oauth_urisProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined;
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    public setAuthorize (value: string): this {
        pushExtension(this.resource, { url: "authorize", valueUri: value } as Extension)
        return this
    }

    public getAuthorize(mode: 'flat'): string | undefined;
    public getAuthorize(mode: 'raw'): Extension | undefined;
    public getAuthorize(): string | undefined;
    public getAuthorize (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "authorize")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueUri")
    }

    public setToken (value: string): this {
        pushExtension(this.resource, { url: "token", valueUri: value } as Extension)
        return this
    }

    public getToken(mode: 'flat'): string | undefined;
    public getToken(mode: 'raw'): Extension | undefined;
    public getToken(): string | undefined;
    public getToken (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "token")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueUri")
    }

    public setRegister (value: string): this {
        pushExtension(this.resource, { url: "register", valueUri: value } as Extension)
        return this
    }

    public getRegister(mode: 'flat'): string | undefined;
    public getRegister(mode: 'raw'): Extension | undefined;
    public getRegister(): string | undefined;
    public getRegister (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "register")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueUri")
    }

    public setManage (value: string): this {
        pushExtension(this.resource, { url: "manage", valueUri: value } as Extension)
        return this
    }

    public getManage(mode: 'flat'): string | undefined;
    public getManage(mode: 'raw'): Extension | undefined;
    public getManage(): string | undefined;
    public getManage (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "manage")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueUri")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "oauth-uris"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "extension"),
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", oauth_urisProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

