// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Duration } from "../../hl7-fhir-r4-core/Duration";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Period } from "../../hl7-fhir-r4-core/Period";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/specimen-processingTime (pkg: hl7.fhir.r4.core#4.0.1)
export class processingTimeProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/specimen-processingTime";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : processingTimeProfile {
        const profile = new processingTimeProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : processingTimeProfile {
        return new processingTimeProfile(resource);
    }

    static createResource () : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/specimen-processingTime",
        })
        return resource;
    }

    static create () : processingTimeProfile {
        return processingTimeProfile.apply(processingTimeProfile.createResource());
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    getValuePeriod () : Period | undefined {
        return this.resource.valuePeriod as Period | undefined;
    }

    setValuePeriod (value: Period) : this {
        Object.assign(this.resource, { valuePeriod: value });
        return this;
    }

    getValueDuration () : Duration | undefined {
        return this.resource.valueDuration as Duration | undefined;
    }

    setValueDuration (value: Duration) : this {
        Object.assign(this.resource, { valueDuration: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "processingTime"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", processingTimeProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valuePeriod","valueDuration"]),
            ],
            warnings: [],
        }
    }

}

