// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/structuredefinition-xml-type (pkg: hl7.fhir.r4.core#4.0.1)
export class xml_typeProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/structuredefinition-xml-type";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : xml_typeProfile {
        const profile = new xml_typeProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : xml_typeProfile {
        return new xml_typeProfile(resource);
    }

    static createResource () : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/structuredefinition-xml-type",
        })
        return resource;
    }

    static create () : xml_typeProfile {
        return xml_typeProfile.apply(xml_typeProfile.createResource());
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    getValueString () : string | undefined {
        return this.resource.valueString as string | undefined;
    }

    setValueString (value: string) : this {
        Object.assign(this.resource, { valueString: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "xml-type"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", xml_typeProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

