// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/minValue (pkg: hl7.fhir.r4.core#4.0.1)
export class minValueProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/minValue";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : minValueProfile {
        const profile = new minValueProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : minValueProfile {
        return new minValueProfile(resource);
    }

    static createResource () : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/minValue",
        })
        return resource;
    }

    static create () : minValueProfile {
        return minValueProfile.apply(minValueProfile.createResource());
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    getValueDate () : string | undefined {
        return this.resource.valueDate as string | undefined;
    }

    setValueDate (value: string) : this {
        Object.assign(this.resource, { valueDate: value });
        return this;
    }

    getValueDateTime () : string | undefined {
        return this.resource.valueDateTime as string | undefined;
    }

    setValueDateTime (value: string) : this {
        Object.assign(this.resource, { valueDateTime: value });
        return this;
    }

    getValueTime () : string | undefined {
        return this.resource.valueTime as string | undefined;
    }

    setValueTime (value: string) : this {
        Object.assign(this.resource, { valueTime: value });
        return this;
    }

    getValueDecimal () : number | undefined {
        return this.resource.valueDecimal as number | undefined;
    }

    setValueDecimal (value: number) : this {
        Object.assign(this.resource, { valueDecimal: value });
        return this;
    }

    getValueInteger () : number | undefined {
        return this.resource.valueInteger as number | undefined;
    }

    setValueInteger (value: number) : this {
        Object.assign(this.resource, { valueInteger: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "minValue"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", minValueProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueDate","valueDateTime","valueTime","valueDecimal","valueInteger"]),
            ],
            warnings: [],
        }
    }

}

