// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    isRawExtensionInput,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type VariantProfileRaw = {
    extension?: Extension[];
}

export type VariantProfileFlat = {
    name?: CodeableConcept;
    id?: CodeableConcept;
    type?: CodeableConcept;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/observation-geneticsVariant (pkg: hl7.fhir.r4.core#4.0.1)
export class VariantProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/observation-geneticsVariant";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : VariantProfile {
        const profile = new VariantProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : VariantProfile {
        return new VariantProfile(resource);
    }

    private static resolveInput (args: VariantProfileRaw | VariantProfileFlat) : Extension[] {
        if (isRawExtensionInput<VariantProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.name !== undefined) {
                result.push({ url: "Name", valueCodeableConcept: args.name } as Extension);
            }
            if (args.id !== undefined) {
                result.push({ url: "Id", valueCodeableConcept: args.id } as Extension);
            }
            if (args.type !== undefined) {
                result.push({ url: "Type", valueCodeableConcept: args.type } as Extension);
            }
            return result;
        }
    }

    static createResource (args?: VariantProfileRaw | VariantProfileFlat) : Extension {
        const resolvedExtensions = VariantProfile.resolveInput(args ?? {});

        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/observation-geneticsVariant",
            extension: resolvedExtensions,
        })
        return resource;
    }

    static create (args?: VariantProfileRaw | VariantProfileFlat) : VariantProfile {
        return VariantProfile.apply(VariantProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    public setName (value: CodeableConcept): this {
        pushExtension(this.resource, { url: "Name", valueCodeableConcept: value } as Extension)
        return this
    }

    public getName(mode: 'flat'): CodeableConcept | undefined;
    public getName(mode: 'raw'): Extension | undefined;
    public getName(): CodeableConcept | undefined;
    public getName (mode: 'flat' | 'raw' = 'flat'): CodeableConcept | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "Name")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<CodeableConcept>(ext, "valueCodeableConcept")
    }

    public setId (value: CodeableConcept): this {
        pushExtension(this.resource, { url: "Id", valueCodeableConcept: value } as Extension)
        return this
    }

    public getId(mode: 'flat'): CodeableConcept | undefined;
    public getId(mode: 'raw'): Extension | undefined;
    public getId(): CodeableConcept | undefined;
    public getId (mode: 'flat' | 'raw' = 'flat'): CodeableConcept | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "Id")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<CodeableConcept>(ext, "valueCodeableConcept")
    }

    public setType (value: CodeableConcept): this {
        pushExtension(this.resource, { url: "Type", valueCodeableConcept: value } as Extension)
        return this
    }

    public getType(mode: 'flat'): CodeableConcept | undefined;
    public getType(mode: 'raw'): Extension | undefined;
    public getType(): CodeableConcept | undefined;
    public getType (mode: 'flat' | 'raw' = 'flat'): CodeableConcept | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "Type")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<CodeableConcept>(ext, "valueCodeableConcept")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "Variant"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", VariantProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

