// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    isRawExtensionInput,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type AncestryProfileRaw = {
    extension: Extension[];
}

export type AncestryProfileFlat = {
    name: CodeableConcept;
    percentage?: number;
    source?: CodeableConcept;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/observation-geneticsAncestry (pkg: hl7.fhir.r4.core#4.0.1)
export class AncestryProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/observation-geneticsAncestry";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : AncestryProfile {
        const profile = new AncestryProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : AncestryProfile {
        return new AncestryProfile(resource);
    }

    private static resolveInput (args: AncestryProfileRaw | AncestryProfileFlat) : Extension[] {
        if (isRawExtensionInput<AncestryProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.name !== undefined) {
                result.push({ url: "Name", valueCodeableConcept: args.name } as Extension);
            }
            if (args.percentage !== undefined) {
                result.push({ url: "Percentage", valueDecimal: args.percentage } as Extension);
            }
            if (args.source !== undefined) {
                result.push({ url: "Source", valueCodeableConcept: args.source } as Extension);
            }
            return result;
        }
    }

    static createResource (args: AncestryProfileRaw | AncestryProfileFlat) : Extension {
        const resolvedExtensions = AncestryProfile.resolveInput(args ?? {});

        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/observation-geneticsAncestry",
            extension: resolvedExtensions,
        })
        return resource;
    }

    static create (args: AncestryProfileRaw | AncestryProfileFlat) : AncestryProfile {
        return AncestryProfile.apply(AncestryProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined;
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    public setName (value: CodeableConcept): this {
        pushExtension(this.resource, { url: "Name", valueCodeableConcept: value } as Extension)
        return this
    }

    public getName(mode: 'flat'): CodeableConcept | undefined;
    public getName(mode: 'raw'): Extension | undefined;
    public getName(): CodeableConcept | undefined;
    public getName (mode: 'flat' | 'raw' = 'flat'): CodeableConcept | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "Name")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<CodeableConcept>(ext, "valueCodeableConcept")
    }

    public setPercentage (value: number): this {
        pushExtension(this.resource, { url: "Percentage", valueDecimal: value } as Extension)
        return this
    }

    public getPercentage(mode: 'flat'): number | undefined;
    public getPercentage(mode: 'raw'): Extension | undefined;
    public getPercentage(): number | undefined;
    public getPercentage (mode: 'flat' | 'raw' = 'flat'): number | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "Percentage")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<number>(ext, "valueDecimal")
    }

    public setSource (value: CodeableConcept): this {
        pushExtension(this.resource, { url: "Source", valueCodeableConcept: value } as Extension)
        return this
    }

    public getSource(mode: 'flat'): CodeableConcept | undefined;
    public getSource(mode: 'raw'): Extension | undefined;
    public getSource(): CodeableConcept | undefined;
    public getSource (mode: 'flat' | 'raw' = 'flat'): CodeableConcept | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "Source")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<CodeableConcept>(ext, "valueCodeableConcept")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "Ancestry"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "extension"),
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", AncestryProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

