// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    isRawExtensionInput,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type glstringProfileRaw = {
    extension?: Extension[];
}

export type glstringProfileFlat = {
    url?: string;
    text?: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/hla-genotyping-results-glstring (pkg: hl7.fhir.r4.core#4.0.1)
export class glstringProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/hla-genotyping-results-glstring";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : glstringProfile {
        const profile = new glstringProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : glstringProfile {
        return new glstringProfile(resource);
    }

    private static resolveInput (args: glstringProfileRaw | glstringProfileFlat) : Extension[] {
        if (isRawExtensionInput<glstringProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.url !== undefined) {
                result.push({ url: "url", valueUri: args.url } as Extension);
            }
            if (args.text !== undefined) {
                result.push({ url: "text", valueString: args.text } as Extension);
            }
            return result;
        }
    }

    static createResource (args?: glstringProfileRaw | glstringProfileFlat) : Extension {
        const resolvedExtensions = glstringProfile.resolveInput(args ?? {});

        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/hla-genotyping-results-glstring",
            extension: resolvedExtensions,
        })
        return resource;
    }

    static create (args?: glstringProfileRaw | glstringProfileFlat) : glstringProfile {
        return glstringProfile.apply(glstringProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    // Extensions
    public setUrl (value: string): this {
        pushExtension(this.resource, { url: "url", valueUri: value } as Extension)
        return this
    }

    public getUrl(mode: 'flat'): string | undefined;
    public getUrl(mode: 'raw'): Extension | undefined;
    public getUrl(): string | undefined;
    public getUrl (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "url")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueUri")
    }

    public setText (value: string): this {
        pushExtension(this.resource, { url: "text", valueString: value } as Extension)
        return this
    }

    public getText(mode: 'flat'): string | undefined;
    public getText(mode: 'raw'): Extension | undefined;
    public getText(): string | undefined;
    public getText (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "text")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueString")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "glstring"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", glstringProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

