// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/elementdefinition-allowedUnits (pkg: hl7.fhir.r4.core#4.0.1)
export class allowedUnitsProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/elementdefinition-allowedUnits";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : allowedUnitsProfile {
        const profile = new allowedUnitsProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : allowedUnitsProfile {
        return new allowedUnitsProfile(resource);
    }

    static createResource () : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-allowedUnits",
        })
        return resource;
    }

    static create () : allowedUnitsProfile {
        return allowedUnitsProfile.apply(allowedUnitsProfile.createResource());
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    getValueCodeableConcept () : CodeableConcept | undefined {
        return this.resource.valueCodeableConcept as CodeableConcept | undefined;
    }

    setValueCodeableConcept (value: CodeableConcept) : this {
        Object.assign(this.resource, { valueCodeableConcept: value });
        return this;
    }

    getValueCanonical () : string | undefined {
        return this.resource.valueCanonical as string | undefined;
    }

    setValueCanonical (value: string) : this {
        Object.assign(this.resource, { valueCanonical: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "allowedUnits"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", allowedUnitsProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueCodeableConcept","valueCanonical"]),
            ],
            warnings: [],
        }
    }

}

