// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Library } from "../../hl7-fhir-r4-core/Library";

import {
    buildResource,
    ensureProfile,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type CQL_LibraryProfileRaw = {
    status: ("draft" | "active" | "retired" | "unknown");
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/cqllibrary (pkg: hl7.fhir.r4.core#4.0.1)
export class CQL_LibraryProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/cqllibrary";

    private resource: Library;

    constructor (resource: Library) {
        this.resource = resource;
    }

    static from (resource: Library) : CQL_LibraryProfile {
        if (!resource.meta?.profile?.includes(CQL_LibraryProfile.canonicalUrl)) {
            throw new Error(`CQL_LibraryProfile: meta.profile must include ${CQL_LibraryProfile.canonicalUrl}`)
        }
        const profile = new CQL_LibraryProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Library) : CQL_LibraryProfile {
        ensureProfile(resource, CQL_LibraryProfile.canonicalUrl);
        return new CQL_LibraryProfile(resource);
    }

    static createResource (args: CQL_LibraryProfileRaw) : Library {
        const resource = buildResource<Library>( {
            resourceType: "Library",
            type: {"coding":[{"system":"http://terminology.hl7.org/CodeSystem/library-type","code":"logic-library","display":"Logic Library"}]},
            status: args.status,
            meta: { profile: [CQL_LibraryProfile.canonicalUrl] },
        })
        return resource;
    }

    static create (args: CQL_LibraryProfileRaw) : CQL_LibraryProfile {
        return CQL_LibraryProfile.apply(CQL_LibraryProfile.createResource(args));
    }

    toResource () : Library {
        return this.resource;
    }

    // Field accessors
    getStatus () : ("draft" | "active" | "retired" | "unknown") | undefined {
        return this.resource.status as ("draft" | "active" | "retired" | "unknown") | undefined;
    }

    setStatus (value: ("draft" | "active" | "retired" | "unknown")) : this {
        Object.assign(this.resource, { status: value });
        return this;
    }

    getType () : CodeableConcept<("logic-library" | "model-definition" | "asset-collection" | "module-definition" | string)> | undefined {
        return this.resource.type as CodeableConcept<("logic-library" | "model-definition" | "asset-collection" | "module-definition" | string)> | undefined;
    }

    setType (value: CodeableConcept<("logic-library" | "model-definition" | "asset-collection" | "module-definition" | string)>) : this {
        Object.assign(this.resource, { type: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "CQL Library"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "type"),
                ...validateFixedValue(res, profileName, "type", {"coding":[{"system":"http://terminology.hl7.org/CodeSystem/library-type","code":"logic-library","display":"Logic Library"}]}),
            ],
            warnings: [
                ...validateEnum(res, profileName, "type", ["logic-library","model-definition","asset-collection","module-definition"]),
                ...validateMustSupport(res, profileName, "parameter"),
                ...validateMustSupport(res, profileName, "dataRequirement"),
            ],
        }
    }

}

