// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Measure } from "../../hl7-fhir-r4-core/Measure";

import {
    buildResource,
    ensureProfile,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type Shareable_MeasureProfileRaw = {
    url: string;
    version: string;
    name: string;
    experimental: boolean;
    publisher: string;
    description: string;
    status: ("draft" | "active" | "retired" | "unknown");
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/shareablemeasure (pkg: hl7.fhir.r4.core#4.0.1)
export class Shareable_MeasureProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/shareablemeasure";

    private resource: Measure;

    constructor (resource: Measure) {
        this.resource = resource;
    }

    static from (resource: Measure) : Shareable_MeasureProfile {
        if (!resource.meta?.profile?.includes(Shareable_MeasureProfile.canonicalUrl)) {
            throw new Error(`Shareable_MeasureProfile: meta.profile must include ${Shareable_MeasureProfile.canonicalUrl}`)
        }
        const profile = new Shareable_MeasureProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Measure) : Shareable_MeasureProfile {
        ensureProfile(resource, Shareable_MeasureProfile.canonicalUrl);
        return new Shareable_MeasureProfile(resource);
    }

    static createResource (args: Shareable_MeasureProfileRaw) : Measure {
        const resource = buildResource<Measure>( {
            resourceType: "Measure",
            url: args.url,
            version: args.version,
            name: args.name,
            experimental: args.experimental,
            publisher: args.publisher,
            description: args.description,
            status: args.status,
            meta: { profile: [Shareable_MeasureProfile.canonicalUrl] },
        })
        return resource;
    }

    static create (args: Shareable_MeasureProfileRaw) : Shareable_MeasureProfile {
        return Shareable_MeasureProfile.apply(Shareable_MeasureProfile.createResource(args));
    }

    toResource () : Measure {
        return this.resource;
    }

    // Field accessors
    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    getVersion () : string | undefined {
        return this.resource.version as string | undefined;
    }

    setVersion (value: string) : this {
        Object.assign(this.resource, { version: value });
        return this;
    }

    getName () : string | undefined {
        return this.resource.name as string | undefined;
    }

    setName (value: string) : this {
        Object.assign(this.resource, { name: value });
        return this;
    }

    getExperimental () : boolean | undefined {
        return this.resource.experimental as boolean | undefined;
    }

    setExperimental (value: boolean) : this {
        Object.assign(this.resource, { experimental: value });
        return this;
    }

    getPublisher () : string | undefined {
        return this.resource.publisher as string | undefined;
    }

    setPublisher (value: string) : this {
        Object.assign(this.resource, { publisher: value });
        return this;
    }

    getDescription () : string | undefined {
        return this.resource.description as string | undefined;
    }

    setDescription (value: string) : this {
        Object.assign(this.resource, { description: value });
        return this;
    }

    getStatus () : ("draft" | "active" | "retired" | "unknown") | undefined {
        return this.resource.status as ("draft" | "active" | "retired" | "unknown") | undefined;
    }

    setStatus (value: ("draft" | "active" | "retired" | "unknown")) : this {
        Object.assign(this.resource, { status: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "Shareable Measure"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateRequired(res, profileName, "version"),
                ...validateRequired(res, profileName, "name"),
                ...validateRequired(res, profileName, "experimental"),
                ...validateRequired(res, profileName, "publisher"),
                ...validateRequired(res, profileName, "description"),
            ],
            warnings: [
                ...validateMustSupport(res, profileName, "identifier"),
                ...validateMustSupport(res, profileName, "title"),
                ...validateMustSupport(res, profileName, "date"),
                ...validateMustSupport(res, profileName, "contact"),
                ...validateMustSupport(res, profileName, "useContext"),
                ...validateMustSupport(res, profileName, "jurisdiction"),
            ],
        }
    }

}

