// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { PlanDefinition } from "../../hl7-fhir-r4-core/PlanDefinition";

import { cdsHooksEndpointProfile } from "./Extension_cdsHooksEndpoint";

import {
    buildResource,
    ensureProfile,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type CDS_Hooks_Service_PlanDefinitionProfileRaw = {
    status: ("draft" | "active" | "retired" | "unknown");
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/cdshooksserviceplandefinition (pkg: hl7.fhir.r4.core#4.0.1)
export class CDS_Hooks_Service_PlanDefinitionProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/cdshooksserviceplandefinition";

    private resource: PlanDefinition;

    constructor (resource: PlanDefinition) {
        this.resource = resource;
    }

    static from (resource: PlanDefinition) : CDS_Hooks_Service_PlanDefinitionProfile {
        if (!resource.meta?.profile?.includes(CDS_Hooks_Service_PlanDefinitionProfile.canonicalUrl)) {
            throw new Error(`CDS_Hooks_Service_PlanDefinitionProfile: meta.profile must include ${CDS_Hooks_Service_PlanDefinitionProfile.canonicalUrl}`)
        }
        const profile = new CDS_Hooks_Service_PlanDefinitionProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: PlanDefinition) : CDS_Hooks_Service_PlanDefinitionProfile {
        ensureProfile(resource, CDS_Hooks_Service_PlanDefinitionProfile.canonicalUrl);
        return new CDS_Hooks_Service_PlanDefinitionProfile(resource);
    }

    static createResource (args: CDS_Hooks_Service_PlanDefinitionProfileRaw) : PlanDefinition {
        const resource = buildResource<PlanDefinition>( {
            resourceType: "PlanDefinition",
            status: args.status,
            meta: { profile: [CDS_Hooks_Service_PlanDefinitionProfile.canonicalUrl] },
        })
        return resource;
    }

    static create (args: CDS_Hooks_Service_PlanDefinitionProfileRaw) : CDS_Hooks_Service_PlanDefinitionProfile {
        return CDS_Hooks_Service_PlanDefinitionProfile.apply(CDS_Hooks_Service_PlanDefinitionProfile.createResource(args));
    }

    toResource () : PlanDefinition {
        return this.resource;
    }

    // Field accessors
    getStatus () : ("draft" | "active" | "retired" | "unknown") | undefined {
        return this.resource.status as ("draft" | "active" | "retired" | "unknown") | undefined;
    }

    setStatus (value: ("draft" | "active" | "retired" | "unknown")) : this {
        Object.assign(this.resource, { status: value });
        return this;
    }

    // Extensions
    public setCdsHooksEndpoint (value: cdsHooksEndpointProfile | Extension | string): this {
        if (value instanceof cdsHooksEndpointProfile) {
            pushExtension(this.resource, value.toResource())
        } else if (isExtension(value)) {
            if (value.url !== "http://hl7.org/fhir/StructureDefinition/cqf-cdsHooksEndpoint") throw new Error(`Expected extension url 'http://hl7.org/fhir/StructureDefinition/cqf-cdsHooksEndpoint', got '${value.url}'`)
            pushExtension(this.resource, value)
        } else {
            pushExtension(this.resource, cdsHooksEndpointProfile.createResource({ valueUri: value as string }))
        }
        return this
    }

    public getCdsHooksEndpoint(mode: 'flat'): string | undefined;
    public getCdsHooksEndpoint(mode: 'profile'): cdsHooksEndpointProfile | undefined;
    public getCdsHooksEndpoint(mode: 'raw'): Extension | undefined;
    public getCdsHooksEndpoint(): string | undefined;
    public getCdsHooksEndpoint (mode: 'flat' | 'profile' | 'raw' = 'flat'): string | cdsHooksEndpointProfile | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-cdsHooksEndpoint")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        if (mode === 'profile') return cdsHooksEndpointProfile.apply(ext)
        return getExtensionValue<string>(ext, "valueUri")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "CDS Hooks Service PlanDefinition"
        const res = this.resource
        return {
            errors: [],
            warnings: [],
        }
    }

}

