// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Quantity } from "../../hl7-fhir-r4-core/Quantity";

import { buildResource } from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/MoneyQuantity (pkg: hl7.fhir.r4.core#4.0.1)
export class MoneyQuantityProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/MoneyQuantity";

    private resource: Quantity;

    constructor (resource: Quantity) {
        this.resource = resource;
    }

    static from (resource: Quantity) : MoneyQuantityProfile {
        const profile = new MoneyQuantityProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Quantity) : MoneyQuantityProfile {
        return new MoneyQuantityProfile(resource);
    }

    static createResource () : Quantity {
        const resource = buildResource<Quantity>( {
        })
        return resource;
    }

    static create () : MoneyQuantityProfile {
        return MoneyQuantityProfile.apply(MoneyQuantityProfile.createResource());
    }

    toResource () : Quantity {
        return this.resource;
    }

    // Field accessors
    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "MoneyQuantity"
        const res = this.resource
        return {
            errors: [],
            warnings: [],
        }
    }

}

