// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Questionnaire } from "../../hl7-fhir-r4-core/Questionnaire";

import { libraryProfile } from "./Extension_library";

import {
    buildResource,
    ensureProfile,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type CQF_QuestionnaireProfileRaw = {
    status: ("draft" | "active" | "retired" | "unknown");
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/cqf-questionnaire (pkg: hl7.fhir.r4.core#4.0.1)
export class CQF_QuestionnaireProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/cqf-questionnaire";

    private resource: Questionnaire;

    constructor (resource: Questionnaire) {
        this.resource = resource;
    }

    static from (resource: Questionnaire) : CQF_QuestionnaireProfile {
        if (!resource.meta?.profile?.includes(CQF_QuestionnaireProfile.canonicalUrl)) {
            throw new Error(`CQF_QuestionnaireProfile: meta.profile must include ${CQF_QuestionnaireProfile.canonicalUrl}`)
        }
        const profile = new CQF_QuestionnaireProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Questionnaire) : CQF_QuestionnaireProfile {
        ensureProfile(resource, CQF_QuestionnaireProfile.canonicalUrl);
        return new CQF_QuestionnaireProfile(resource);
    }

    static createResource (args: CQF_QuestionnaireProfileRaw) : Questionnaire {
        const resource = buildResource<Questionnaire>( {
            resourceType: "Questionnaire",
            status: args.status,
            meta: { profile: [CQF_QuestionnaireProfile.canonicalUrl] },
        })
        return resource;
    }

    static create (args: CQF_QuestionnaireProfileRaw) : CQF_QuestionnaireProfile {
        return CQF_QuestionnaireProfile.apply(CQF_QuestionnaireProfile.createResource(args));
    }

    toResource () : Questionnaire {
        return this.resource;
    }

    // Field accessors
    getStatus () : ("draft" | "active" | "retired" | "unknown") | undefined {
        return this.resource.status as ("draft" | "active" | "retired" | "unknown") | undefined;
    }

    setStatus (value: ("draft" | "active" | "retired" | "unknown")) : this {
        Object.assign(this.resource, { status: value });
        return this;
    }

    // Extensions
    public setLibrary (value: libraryProfile | Extension | string): this {
        if (value instanceof libraryProfile) {
            pushExtension(this.resource, value.toResource())
        } else if (isExtension(value)) {
            if (value.url !== "http://hl7.org/fhir/StructureDefinition/cqf-library") throw new Error(`Expected extension url 'http://hl7.org/fhir/StructureDefinition/cqf-library', got '${value.url}'`)
            pushExtension(this.resource, value)
        } else {
            pushExtension(this.resource, libraryProfile.createResource({ valueCanonical: value as string }))
        }
        return this
    }

    public getLibrary(mode: 'flat'): string | undefined;
    public getLibrary(mode: 'profile'): libraryProfile | undefined;
    public getLibrary(mode: 'raw'): Extension | undefined;
    public getLibrary(): string | undefined;
    public getLibrary (mode: 'flat' | 'profile' | 'raw' = 'flat'): string | libraryProfile | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-library")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        if (mode === 'profile') return libraryProfile.apply(ext)
        return getExtensionValue<string>(ext, "valueCanonical")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "CQF-Questionnaire"
        const res = this.resource
        return {
            errors: [],
            warnings: [],
        }
    }

}

