// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { ValueSet } from "../../hl7-fhir-r4-core/ValueSet";

import {
    buildResource,
    ensureProfile,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type Shareable_ValueSetProfileRaw = {
    url: string;
    version: string;
    name: string;
    status: ("draft" | "active" | "retired" | "unknown");
    experimental: boolean;
    publisher: string;
    description: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/shareablevalueset (pkg: hl7.fhir.r4.core#4.0.1)
export class Shareable_ValueSetProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/shareablevalueset";

    private resource: ValueSet;

    constructor (resource: ValueSet) {
        this.resource = resource;
    }

    static from (resource: ValueSet) : Shareable_ValueSetProfile {
        if (!resource.meta?.profile?.includes(Shareable_ValueSetProfile.canonicalUrl)) {
            throw new Error(`Shareable_ValueSetProfile: meta.profile must include ${Shareable_ValueSetProfile.canonicalUrl}`)
        }
        const profile = new Shareable_ValueSetProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: ValueSet) : Shareable_ValueSetProfile {
        ensureProfile(resource, Shareable_ValueSetProfile.canonicalUrl);
        return new Shareable_ValueSetProfile(resource);
    }

    static createResource (args: Shareable_ValueSetProfileRaw) : ValueSet {
        const resource = buildResource<ValueSet>( {
            resourceType: "ValueSet",
            url: args.url,
            version: args.version,
            name: args.name,
            status: args.status,
            experimental: args.experimental,
            publisher: args.publisher,
            description: args.description,
            meta: { profile: [Shareable_ValueSetProfile.canonicalUrl] },
        })
        return resource;
    }

    static create (args: Shareable_ValueSetProfileRaw) : Shareable_ValueSetProfile {
        return Shareable_ValueSetProfile.apply(Shareable_ValueSetProfile.createResource(args));
    }

    toResource () : ValueSet {
        return this.resource;
    }

    // Field accessors
    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    getVersion () : string | undefined {
        return this.resource.version as string | undefined;
    }

    setVersion (value: string) : this {
        Object.assign(this.resource, { version: value });
        return this;
    }

    getName () : string | undefined {
        return this.resource.name as string | undefined;
    }

    setName (value: string) : this {
        Object.assign(this.resource, { name: value });
        return this;
    }

    getStatus () : ("draft" | "active" | "retired" | "unknown") | undefined {
        return this.resource.status as ("draft" | "active" | "retired" | "unknown") | undefined;
    }

    setStatus (value: ("draft" | "active" | "retired" | "unknown")) : this {
        Object.assign(this.resource, { status: value });
        return this;
    }

    getExperimental () : boolean | undefined {
        return this.resource.experimental as boolean | undefined;
    }

    setExperimental (value: boolean) : this {
        Object.assign(this.resource, { experimental: value });
        return this;
    }

    getPublisher () : string | undefined {
        return this.resource.publisher as string | undefined;
    }

    setPublisher (value: string) : this {
        Object.assign(this.resource, { publisher: value });
        return this;
    }

    getDescription () : string | undefined {
        return this.resource.description as string | undefined;
    }

    setDescription (value: string) : this {
        Object.assign(this.resource, { description: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "Shareable ValueSet"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateRequired(res, profileName, "version"),
                ...validateRequired(res, profileName, "name"),
                ...validateRequired(res, profileName, "status"),
                ...validateEnum(res, profileName, "status", ["draft","active","retired","unknown"]),
                ...validateRequired(res, profileName, "experimental"),
                ...validateRequired(res, profileName, "publisher"),
                ...validateRequired(res, profileName, "description"),
            ],
            warnings: [],
        }
    }

}

