-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/appointment.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM {{ delta_table('silver', 'appointment') }}
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "appointment_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."cancelationReason"'), '$."text"')) AS "cancelation_reason_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."cancelationReason"'), '$."coding"')[1:1], '$."code"')) AS "cancelation_reason_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."cancelationReason"'), '$."coding"')[1:1], '$."system"')) AS "cancelation_reason_system",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."appointmentType"'), '$."text"')) AS "appointment_type_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."appointmentType"'), '$."coding"')[1:1], '$."code"')) AS "appointment_type_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."appointmentType"'), '$."coding"')[1:1], '$."system"')) AS "appointment_type_system",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."reasonReference"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS VARCHAR) AS "reason_reference_ids",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."priority"')) AS INTEGER) AS "priority",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."description"')) AS "description",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."supportingInformation"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS VARCHAR) AS "supporting_information_ids",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."start"')) AS "start",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."end"')) AS "end",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."minutesDuration"')) AS INTEGER) AS "minutes_duration",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."slot"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS VARCHAR) AS "slot_ids",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."created"')) AS "created",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."comment"')) AS "comment",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."patientInstruction"')) AS "patient_instruction",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."basedOn"'), sof_r7 -> to_json(nullif(regexp_extract(json_extract_string(sof_r7, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y8 -> sof_y8 IS NOT NULL)) AS VARCHAR) AS "based_on_ids"
FROM sof_src
