-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/bundle.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM {{ delta_table('silver', 'bundle') }}
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "bundle_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."identifier"'), '$."value"')) AS "identifier_value",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."identifier"'), '$."system"')) AS "identifier_system",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."type"')) AS "type",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."timestamp"')) AS "timestamp",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."total"')) AS INTEGER) AS "total"
FROM sof_src
