-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/compartment_definition.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM {{ delta_table('silver', 'compartmentdefinition') }}
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "compartment_definition_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."url"')) AS "url",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."version"')) AS "version",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."name"')) AS "name",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."experimental"')) AS BOOLEAN) AS "experimental",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."date"')) AS "date",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."publisher"')) AS "publisher",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."description"')) AS "description",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."purpose"')) AS "purpose",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."code"')) AS "code",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."search"')) AS BOOLEAN) AS "search"
FROM sof_src
