-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/composition.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM {{ delta_table('silver', 'composition') }}
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "composition_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."identifier"'), '$."value"')) AS "identifier_value",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."identifier"'), '$."system"')) AS "identifier_system",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."text"')) AS "type_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."coding"')[1:1], '$."code"')) AS "type_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."coding"')[1:1], '$."system"')) AS "type_system",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."subject"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS "subject_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."subject"'), '$."reference"')) AS "subject_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."encounter"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS "encounter_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."encounter"'), '$."reference"')) AS "encounter_reference",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."date"')) AS "date",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."author"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS VARCHAR) AS "author_ids",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."title"')) AS "title",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."confidentiality"')) AS "confidentiality",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."custodian"'), sof_r7 -> to_json(nullif(regexp_extract(json_extract_string(sof_r7, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y8 -> sof_y8 IS NOT NULL)) AS "custodian_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."custodian"'), '$."reference"')) AS "custodian_reference"
FROM sof_src
