-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/contract.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM {{ delta_table('silver', 'contract') }}
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "contract_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."url"')) AS "url",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."version"')) AS "version",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."legalState"'), '$."text"')) AS "legal_state_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."legalState"'), '$."coding"')[1:1], '$."code"')) AS "legal_state_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."legalState"'), '$."coding"')[1:1], '$."system"')) AS "legal_state_system",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."instantiatesCanonical"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS "instantiates_canonical_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."instantiatesCanonical"'), '$."reference"')) AS "instantiates_canonical_reference",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."instantiatesUri"')) AS "instantiates_uri",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."contentDerivative"'), '$."text"')) AS "content_derivative_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."contentDerivative"'), '$."coding"')[1:1], '$."code"')) AS "content_derivative_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."contentDerivative"'), '$."coding"')[1:1], '$."system"')) AS "content_derivative_system",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."issued"')) AS "issued",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."expirationType"'), '$."text"')) AS "expiration_type_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."expirationType"'), '$."coding"')[1:1], '$."code"')) AS "expiration_type_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."expirationType"'), '$."coding"')[1:1], '$."system"')) AS "expiration_type_system",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."subject"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS VARCHAR) AS "subject_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."authority"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS VARCHAR) AS "authority_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."domain"'), sof_r7 -> to_json(nullif(regexp_extract(json_extract_string(sof_r7, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y8 -> sof_y8 IS NOT NULL)) AS VARCHAR) AS "domain_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."site"'), sof_r9 -> to_json(nullif(regexp_extract(json_extract_string(sof_r9, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y10 -> sof_y10 IS NOT NULL)) AS VARCHAR) AS "site_ids",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."name"')) AS "name",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."title"')) AS "title",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."subtitle"')) AS "subtitle",
  CAST(to_json(sof_get(sof_wrap(sof_src.resource), '$."alias"')) AS VARCHAR) AS "alias",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."author"'), sof_r11 -> to_json(nullif(regexp_extract(json_extract_string(sof_r11, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y12 -> sof_y12 IS NOT NULL)) AS "author_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."author"'), '$."reference"')) AS "author_reference",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."scope"'), '$."text"')) AS "scope_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."scope"'), '$."coding"')[1:1], '$."code"')) AS "scope_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."scope"'), '$."coding"')[1:1], '$."system"')) AS "scope_system",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."topicReference"'), sof_r13 -> to_json(nullif(regexp_extract(json_extract_string(sof_r13, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y14 -> sof_y14 IS NOT NULL)) AS "topic_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."text"')) AS "type_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."coding"')[1:1], '$."code"')) AS "type_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."coding"')[1:1], '$."system"')) AS "type_system",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."supportingInfo"'), sof_r15 -> to_json(nullif(regexp_extract(json_extract_string(sof_r15, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y16 -> sof_y16 IS NOT NULL)) AS VARCHAR) AS "supporting_info_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."relevantHistory"'), sof_r17 -> to_json(nullif(regexp_extract(json_extract_string(sof_r17, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y18 -> sof_y18 IS NOT NULL)) AS VARCHAR) AS "relevant_history_ids",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."legallyBindingReference"'), sof_r19 -> to_json(nullif(regexp_extract(json_extract_string(sof_r19, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y20 -> sof_y20 IS NOT NULL)) AS "legally_binding_id"
FROM sof_src
