-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/device.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM {{ delta_table('silver', 'device') }}
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "device_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."definition"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS "definition_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."definition"'), '$."reference"')) AS "definition_reference",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."distinctIdentifier"')) AS "distinct_identifier",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."manufacturer"')) AS "manufacturer",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."manufactureDate"')) AS "manufacture_date",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."expirationDate"')) AS "expiration_date",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."lotNumber"')) AS "lot_number",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."serialNumber"')) AS "serial_number",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."modelNumber"')) AS "model_number",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."partNumber"')) AS "part_number",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."text"')) AS "type_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."coding"')[1:1], '$."code"')) AS "type_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."coding"')[1:1], '$."system"')) AS "type_system",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."patient"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS "patient_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."patient"'), '$."reference"')) AS "patient_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."owner"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS "owner_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."owner"'), '$."reference"')) AS "owner_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."location"'), sof_r7 -> to_json(nullif(regexp_extract(json_extract_string(sof_r7, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y8 -> sof_y8 IS NOT NULL)) AS "location_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."location"'), '$."reference"')) AS "location_reference",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."url"')) AS "url",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."parent"'), sof_r9 -> to_json(nullif(regexp_extract(json_extract_string(sof_r9, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y10 -> sof_y10 IS NOT NULL)) AS "parent_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."parent"'), '$."reference"')) AS "parent_reference"
FROM sof_src
