-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/device_definition.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM {{ delta_table('silver', 'devicedefinition') }}
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "device_definition_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."manufacturerString"')) AS "manufacturer_string",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."manufacturerReference"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS "manufacturer_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."modelNumber"')) AS "model_number",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."text"')) AS "type_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."coding"')[1:1], '$."code"')) AS "type_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."coding"')[1:1], '$."system"')) AS "type_system",
  CAST(to_json(sof_get(sof_wrap(sof_src.resource), '$."version"')) AS VARCHAR) AS "version",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."owner"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS "owner_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."owner"'), '$."reference"')) AS "owner_reference",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."url"')) AS "url",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."onlineInformation"')) AS "online_information",
  CAST(sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."quantity"'), '$."value"')) AS DOUBLE) AS "quantity_value",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."quantity"'), '$."unit"')) AS "quantity_unit",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."quantity"'), '$."code"')) AS "quantity_code",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."parentDevice"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS "parent_device_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."parentDevice"'), '$."reference"')) AS "parent_device_reference"
FROM sof_src
