-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/encounter.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM {{ delta_table('silver', 'encounter') }}
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "encounter_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."class"'), '$."code"')) AS "class_code",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."class"'), '$."system"')) AS "class_system",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."class"'), '$."display"')) AS "class_display",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."serviceType"'), '$."text"')) AS "service_type_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."serviceType"'), '$."coding"')[1:1], '$."code"')) AS "service_type_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."serviceType"'), '$."coding"')[1:1], '$."system"')) AS "service_type_system",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."priority"'), '$."text"')) AS "priority_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."priority"'), '$."coding"')[1:1], '$."code"')) AS "priority_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."priority"'), '$."coding"')[1:1], '$."system"')) AS "priority_system",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."subject"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS "subject_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."subject"'), '$."reference"')) AS "subject_reference",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."episodeOfCare"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS VARCHAR) AS "episode_of_care_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."basedOn"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS VARCHAR) AS "based_on_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."appointment"'), sof_r7 -> to_json(nullif(regexp_extract(json_extract_string(sof_r7, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y8 -> sof_y8 IS NOT NULL)) AS VARCHAR) AS "appointment_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."reasonReference"'), sof_r9 -> to_json(nullif(regexp_extract(json_extract_string(sof_r9, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y10 -> sof_y10 IS NOT NULL)) AS VARCHAR) AS "reason_reference_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."account"'), sof_r11 -> to_json(nullif(regexp_extract(json_extract_string(sof_r11, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y12 -> sof_y12 IS NOT NULL)) AS VARCHAR) AS "account_ids",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."serviceProvider"'), sof_r13 -> to_json(nullif(regexp_extract(json_extract_string(sof_r13, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y14 -> sof_y14 IS NOT NULL)) AS "service_provider_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."serviceProvider"'), '$."reference"')) AS "service_provider_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."partOf"'), sof_r15 -> to_json(nullif(regexp_extract(json_extract_string(sof_r15, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y16 -> sof_y16 IS NOT NULL)) AS "part_of_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."partOf"'), '$."reference"')) AS "part_of_reference"
FROM sof_src
