-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/evidence_variable.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM {{ delta_table('silver', 'evidencevariable') }}
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "evidence_variable_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."url"')) AS "url",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."version"')) AS "version",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."name"')) AS "name",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."title"')) AS "title",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."shortTitle"')) AS "short_title",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."subtitle"')) AS "subtitle",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."date"')) AS "date",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."publisher"')) AS "publisher",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."description"')) AS "description",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."copyright"')) AS "copyright",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."approvalDate"')) AS DATE) AS "approval_date",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."lastReviewDate"')) AS DATE) AS "last_review_date",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."type"')) AS "type"
FROM sof_src
