-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/media.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM {{ delta_table('silver', 'media') }}
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "media_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."basedOn"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS VARCHAR) AS "based_on_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."partOf"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS VARCHAR) AS "part_of_ids",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."text"')) AS "type_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."coding"')[1:1], '$."code"')) AS "type_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."type"'), '$."coding"')[1:1], '$."system"')) AS "type_system",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."modality"'), '$."text"')) AS "modality_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."modality"'), '$."coding"')[1:1], '$."code"')) AS "modality_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."modality"'), '$."coding"')[1:1], '$."system"')) AS "modality_system",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."view"'), '$."text"')) AS "view_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."view"'), '$."coding"')[1:1], '$."code"')) AS "view_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."view"'), '$."coding"')[1:1], '$."system"')) AS "view_system",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."subject"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS "subject_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."subject"'), '$."reference"')) AS "subject_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."encounter"'), sof_r7 -> to_json(nullif(regexp_extract(json_extract_string(sof_r7, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y8 -> sof_y8 IS NOT NULL)) AS "encounter_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."encounter"'), '$."reference"')) AS "encounter_reference",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."createdDateTime"')) AS "created_date_time",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."issued"')) AS "issued",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."operator"'), sof_r9 -> to_json(nullif(regexp_extract(json_extract_string(sof_r9, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y10 -> sof_y10 IS NOT NULL)) AS "operator_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."operator"'), '$."reference"')) AS "operator_reference",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."bodySite"'), '$."text"')) AS "body_site_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."bodySite"'), '$."coding"')[1:1], '$."code"')) AS "body_site_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."bodySite"'), '$."coding"')[1:1], '$."system"')) AS "body_site_system",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."deviceName"')) AS "device_name",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."device"'), sof_r11 -> to_json(nullif(regexp_extract(json_extract_string(sof_r11, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y12 -> sof_y12 IS NOT NULL)) AS "device_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."device"'), '$."reference"')) AS "device_reference",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."height"')) AS INTEGER) AS "height",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."width"')) AS INTEGER) AS "width",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."frames"')) AS INTEGER) AS "frames",
  CAST(sof_text(sof_get(sof_wrap(sof_src.resource), '$."duration"')) AS DOUBLE) AS "duration"
FROM sof_src
