-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/base/research_study.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM {{ delta_table('silver', 'researchstudy') }}
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "research_study_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."implicitRules"')) AS "implicit_rules",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."language"')) AS "language",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."title"')) AS "title",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."protocol"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS VARCHAR) AS "protocol_ids",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."partOf"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS VARCHAR) AS "part_of_ids",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."primaryPurposeType"'), '$."text"')) AS "primary_purpose_type_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."primaryPurposeType"'), '$."coding"')[1:1], '$."code"')) AS "primary_purpose_type_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."primaryPurposeType"'), '$."coding"')[1:1], '$."system"')) AS "primary_purpose_type_system",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."phase"'), '$."text"')) AS "phase_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."phase"'), '$."coding"')[1:1], '$."code"')) AS "phase_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."phase"'), '$."coding"')[1:1], '$."system"')) AS "phase_system",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."description"')) AS "description",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."enrollment"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS VARCHAR) AS "enrollment_ids",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."sponsor"'), sof_r7 -> to_json(nullif(regexp_extract(json_extract_string(sof_r7, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y8 -> sof_y8 IS NOT NULL)) AS "sponsor_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."sponsor"'), '$."reference"')) AS "sponsor_reference",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."principalInvestigator"'), sof_r9 -> to_json(nullif(regexp_extract(json_extract_string(sof_r9, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y10 -> sof_y10 IS NOT NULL)) AS "principal_investigator_id",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."principalInvestigator"'), '$."reference"')) AS "principal_investigator_reference",
  CAST(to_json(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."site"'), sof_r11 -> to_json(nullif(regexp_extract(json_extract_string(sof_r11, '$.reference'), '(?:^|/)[A-Za-z]+/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y12 -> sof_y12 IS NOT NULL)) AS VARCHAR) AS "site_ids",
  sof_text(sof_get(sof_get(sof_wrap(sof_src.resource), '$."reasonStopped"'), '$."text"')) AS "reason_stopped_text",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."reasonStopped"'), '$."coding"')[1:1], '$."code"')) AS "reason_stopped_code",
  sof_text(sof_get(sof_get(sof_get(sof_wrap(sof_src.resource), '$."reasonStopped"'), '$."coding"')[1:1], '$."system"')) AS "reason_stopped_system"
FROM sof_src
