/**
 * R4 Core registry — the vendored clean-room columnar schemas for all 146 concrete
 * FHIR R4 Core resource types (generated by scripts/generate-r4-schemas.ts from the
 * CC0 StructureDefinitions). This is the runtime source of truth: the server never
 * parses StructureDefinitions at runtime (works in-container, no FHIR cache).
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type { Column } from "./clean-room-flattener.js";

interface Registry {
  fhirVersion: string;
  resourceTypes: string[];
  schemas: Record<string, Column[]>;
  constraints: Record<string, Array<{ path: string; key: string; expression: string }>>;
}

const registry: Registry = JSON.parse(
  readFileSync(fileURLToPath(new URL("./r4-core-schemas.json", import.meta.url)), "utf8"),
);

/** All 146 concrete R4 Core resource types. */
export const r4CoreResourceTypes: readonly string[] = registry.resourceTypes;
const typeSet = new Set(registry.resourceTypes);

export function isR4CoreResource(resourceType: string): boolean {
  return typeSet.has(resourceType);
}

/** Vendored flattening schema for a resource type. Throws if not an R4 Core type. */
export function schemaFor(resourceType: string): Column[] {
  const s = registry.schemas[resourceType];
  if (!s) throw new Error(`No R4 Core schema for resource type '${resourceType}'`);
  return s;
}

/** Error-severity FHIRPath invariants (L4) for a resource type ([] if none/unknown). */
export function constraintsFor(resourceType: string): Array<{ path: string; key: string; expression: string }> {
  return registry.constraints?.[resourceType] ?? [];
}
