-- GENERATED by `python -m fhirhouse_views.dbt_gen` from views/definitions/medication_request_flat.ViewDefinition.json
-- Do not hand-edit; edit the ViewDefinition and regenerate (FH-0005: the
-- ViewDefinition is the only source artifact).

WITH sof_src AS (
SELECT CAST(body_json AS JSON) AS resource, fhir_id AS resource_key
FROM {{ delta_table('silver', 'medicationrequest') }}
WHERE NOT coalesce(deleted, FALSE)
)
SELECT
  sof_text(sof_wrap(to_json(sof_src.resource_key))) AS "medication_request_id",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."subject"'), sof_r1 -> to_json(nullif(regexp_extract(json_extract_string(sof_r1, '$.reference'), '(?:^|/)Patient/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y2 -> sof_y2 IS NOT NULL)) AS "patient_id",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."encounter"'), sof_r3 -> to_json(nullif(regexp_extract(json_extract_string(sof_r3, '$.reference'), '(?:^|/)Encounter/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y4 -> sof_y4 IS NOT NULL)) AS "encounter_id",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."status"')) AS "status",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."intent"')) AS "intent",
  sof_text(sof_get(sof_wrap(sof_src.resource), '$."authoredOn"')) AS "authored_on",
  sof_text(list_filter(list_transform(sof_get(sof_wrap(sof_src.resource), '$."medicationReference"'), sof_r5 -> to_json(nullif(regexp_extract(json_extract_string(sof_r5, '$.reference'), '(?:^|/)Medication/([A-Za-z0-9\-\.]{1,64})$', 1), ''))), sof_y6 -> sof_y6 IS NOT NULL)) AS "medication_reference_id",
  sof_text(sof_get(sof_wrap(sof_fe7.v), '$."system"')) AS "medication_system",
  sof_text(sof_get(sof_wrap(sof_fe7.v), '$."code"')) AS "medication_code",
  sof_text(sof_get(sof_wrap(sof_fe7.v), '$."display"')) AS "medication_display"
FROM sof_src
LEFT JOIN LATERAL (SELECT unnest(sof_get(sof_get(sof_wrap(sof_src.resource), '$."medicationCodeableConcept"'), '$."coding"')[1:1]) AS v, unnest(range(len(sof_get(sof_get(sof_wrap(sof_src.resource), '$."medicationCodeableConcept"'), '$."coding"')[1:1]))) AS ord) AS sof_fe7 ON TRUE
